#!/usr/bin/env python3
"""
Benchmark + correctness-check the in-tree P-256 ecdsa_verify on a real
Ultimate 64 Elite, at 48 MHz turbo (primary) and optionally 1 MHz.

Drives the UCI-build PRG, boots it to the main_loop, quits to BASIC,
DMA-injects a 6502 stub at $4200 that:

  1. Banks out BASIC ROM so the ECDSA data buffers at $B0xx are RAM-visible.
  2. Writes a "running" sentinel ($AA) at $4540.
  3. Calls ecdsa_verify.
  4. PHP/PLA-captures the P register into $4542 (bit 0 = carry).
  5. Writes a "done" sentinel ($55) at $4541.
  6. Parks.

The host pre-loads pubkey_x/y, hash, sig_r, sig_s, sig_len=32, hash_len=32,
curve_id=0 into the ecdsa_* buffers via DMA, then triggers the stub and
polls the done-sentinel with wall-clock timing around the *transition*
from running->done. That gives us the on-device wall-clock for the
verify call itself, not the SYS-dispatch or keyboard plumbing.

The test vectors come from tools/uci/_ecdsa_vectors.json (generated by
_ecdsa_vectors.py). Set ECDSA_VECTORS_JSON to override the path.

Env:
  U64_HOST         — default 192.168.1.81
  ECDSA_MHZ_LIST   — comma list, default "48"; include "1" for a 1 MHz
                     baseline (expect 10-30 min at 1 MHz).
  ECDSA_REPEATS    — repeats per vector at each speed; default 3 for
                     positive, 1 for negative.
  ECDSA_POLL_S     — poll interval (s) for done-sentinel; default 0.10.
  ECDSA_TIMEOUT_S  — per-run timeout. Default 180s at 48 MHz,
                     2400s at 1 MHz.
  ECDSA_DEBUG_CAPTURE — "1" to enable U64 6510 debug-stream capture for
                     the FIRST 48 MHz positive run; artifacts written
                     under $ECDSA_DEBUG_DIR (default /tmp/ecdsa_debug/).
  KEEP_DEBUG_ON_PASS — as in test_https_local.py.
"""
from __future__ import annotations

import datetime
import json
import os
import shutil
import struct
import subprocess
import sys
import time
import traceback
from pathlib import Path

from c64_test_harness.backends.device_lock import DeviceLock
from c64_test_harness.labels import Labels
from c64_test_harness.backends.ultimate64 import Ultimate64Transport
from c64_test_harness.backends.ultimate64_client import Ultimate64Client
from c64_test_harness.backends.ultimate64_helpers import (
    set_turbo_mhz,
    set_debug_stream_mode,
    DEBUG_MODE_6510,
)
from c64_test_harness.backends.u64_debug_capture import (
    DebugCapture,
    DEFAULT_DEBUG_PORT,
)
from c64_test_harness.uci_network import enable_uci, disable_uci
from c64_test_harness.keyboard import send_text

from _memory_policy import build_policy_and_arbiter


HOST = os.environ.get("U64_HOST", "192.168.1.81")
REPO_ROOT = Path(__file__).resolve().parents[2]
PRG_PATH = REPO_ROOT / "build" / "c64-https.prg"
LABELS_PATH = REPO_ROOT / "build" / "labels.txt"
VECTORS_PATH = Path(
    os.environ.get(
        "ECDSA_VECTORS_JSON",
        str(Path(__file__).with_name("_ecdsa_vectors.json")),
    )
)

# Scratch addresses are arbiter-allocated at runtime (see main()) so the
# bench never collides with X25519_RODATA/BSS under USE_X25519_SIBLING=1
# or with any future CRYPTO_OVERLAY-resident segment.  The historical
# values were $4200 (ROUTINE_ADDR) + $4540-$4543 — *inside* the
# X25519_RODATA + X25519_BSS span under the sibling flag.
ROUTINE_ADDR: int = -1   # arbiter.alloc(320, name="ecdsa_stub")
RUN_SENTINEL: int = -1   # arbiter.alloc(1,   name="run_sentinel")
DONE_SENTINEL: int = -1  # arbiter.alloc(1,   name="done_sentinel")
CARRY_BYTE: int = -1     # arbiter.alloc(1,   name="carry_byte")
PROGRESS_BYTE: int = -1  # arbiter.alloc(1,   name="progress_byte")

RUN_VALUE  = 0xAA
DONE_VALUE = 0x55

MHZ_LIST = [int(x) for x in os.environ.get("ECDSA_MHZ_LIST", "48").split(",")
            if x.strip()]
REPEATS_POS = int(os.environ.get("ECDSA_REPEATS", "3"))
REPEATS_NEG = 1
POLL_S = float(os.environ.get("ECDSA_POLL_S", "2.0"))

DEBUG_CAPTURE = os.environ.get("ECDSA_DEBUG_CAPTURE", "0") == "1"
DEBUG_BASE_DIR = Path(os.environ.get("ECDSA_DEBUG_DIR", "/tmp/ecdsa_debug"))
KEEP_ON_PASS = os.environ.get("KEEP_DEBUG_ON_PASS", "0") == "1"


def _load_labels() -> dict[str, int]:
    # c64-test-harness Labels is a Mapping since 0.12.4 (JC-000/c64-test-harness#64)
    # and parses both C: and non-C (REU/bank) label lines since #62.
    return dict(Labels.from_file(LABELS_PATH))


def _build_stub(labels: dict[str, int]) -> bytes:
    """Emit the 6502 stub that runs ONE ecdsa_verify call and signals."""
    code = bytearray()

    def emit(*bs: int) -> None:
        code.extend(bs)

    def emit_lda_imm(v: int) -> None: emit(0xA9, v & 0xFF)
    def emit_sta_abs(a: int) -> None: emit(0x8D, a & 0xFF, (a >> 8) & 0xFF)
    def emit_lda_abs(a: int) -> None: emit(0xAD, a & 0xFF, (a >> 8) & 0xFF)
    def emit_jsr(a: int) -> None:     emit(0x20, a & 0xFF, (a >> 8) & 0xFF)
    def emit_jmp(a: int) -> None:     emit(0x4C, a & 0xFF, (a >> 8) & 0xFF)

    ecdsa_verify = labels["ecdsa_verify"]

    # 0) Bank BASIC ROM OUT — ecdsa data buffers live at $B0xx (SHADOW_BSS).
    emit_lda_abs(0x0001)
    emit(0x29, 0xFE)           # AND #$FE
    emit_sta_abs(0x0001)

    # Clear markers
    emit_lda_imm(0x00)
    emit_sta_abs(DONE_SENTINEL)
    emit_sta_abs(CARRY_BYTE)
    emit_sta_abs(PROGRESS_BYTE)

    # "running" sentinel
    emit_lda_imm(RUN_VALUE)
    emit_sta_abs(RUN_SENTINEL)

    # progress = 1 (pre-call)
    emit_lda_imm(0x01)
    emit_sta_abs(PROGRESS_BYTE)

    # jsr ecdsa_verify
    emit_jsr(ecdsa_verify)

    # Save carry via PHP/PLA to CARRY_BYTE (bit 0 = C)
    emit(0x08)                 # PHP
    emit(0x68)                 # PLA
    emit_sta_abs(CARRY_BYTE)

    # progress = 2 (post-call)
    emit_lda_imm(0x02)
    emit_sta_abs(PROGRESS_BYTE)

    # done sentinel
    emit_lda_imm(DONE_VALUE)
    emit_sta_abs(DONE_SENTINEL)

    # clear running sentinel
    emit_lda_imm(0x00)
    emit_sta_abs(RUN_SENTINEL)

    # Return to BASIC so the next `sys` can be queued.
    # BASIC expects BASIC ROM banked in; do that before RTS.
    emit_lda_abs(0x0001)
    emit(0x09, 0x01)           # ORA #$01
    emit_sta_abs(0x0001)
    emit(0x60)                 # RTS

    return bytes(code)


def _prepare_vector_buffers(transport: Ultimate64Transport,
                            labels: dict[str, int],
                            vec: dict) -> None:
    """DMA-write all ecdsa_* input buffers from a JSON vector dict."""
    # Zero-fill first (buffers are 48 bytes each to handle P-384 hypothetical);
    # verify_256 reads the first 32 only but pre-zeroing is paranoid-safe.
    # These buffers legitimately live inside CRYPTO_COLD_SHADOW
    # ($A000-$BFFF) post-W1, which the MemoryPolicy reserves — override
    # with a reason rather than widening the policy for everyone.
    _OVR = "ecdsa vector input buffers (CRYPTO_BSS in CRYPTO_COLD_SHADOW)"
    zero48 = bytes(48)
    for name in ("ecdsa_hash", "ecdsa_sig_r", "ecdsa_sig_s",
                 "ecdsa_pubkey_x", "ecdsa_pubkey_y"):
        transport.write_memory(labels[name], zero48, override=_OVR)

    # Write the 32-byte big-endian values verbatim.
    def _write_be32(name: str, hex_str: str) -> None:
        raw = bytes.fromhex(hex_str)
        assert len(raw) == 32, f"{name}: expected 32 bytes, got {len(raw)}"
        transport.write_memory(labels[name], raw, override=_OVR)

    _write_be32("ecdsa_hash", vec["hash"])
    _write_be32("ecdsa_sig_r", vec["sig_r"])
    _write_be32("ecdsa_sig_s", vec["sig_s"])
    _write_be32("ecdsa_pubkey_x", vec["pubkey_x"])
    _write_be32("ecdsa_pubkey_y", vec["pubkey_y"])

    # Control bytes.
    transport.write_memory(labels["ecdsa_curve_id"], bytes([0]), override=_OVR)
    transport.write_memory(labels["ecdsa_hash_len"], bytes([32]), override=_OVR)
    transport.write_memory(labels["ecdsa_sig_len"], bytes([32]), override=_OVR)


def _run_single(transport: Ultimate64Transport,
                client: Ultimate64Client,
                labels: dict[str, int],
                vec: dict,
                mhz: int,
                timeout_s: float) -> dict:
    """Run one ecdsa_verify on the U64E. Returns a dict with timing + carry."""
    # Clear sentinels ahead of time and stage inputs.
    transport.write_memory(RUN_SENTINEL, bytes([0, 0, 0, 0]))  # 4540-4543
    _prepare_vector_buffers(transport, labels, vec)

    # Set turbo (idempotent — set each run in case the machine reset it).
    set_turbo_mhz(client, mhz)
    time.sleep(0.3)

    # Give BASIC a moment to be ready (after previous run's RTS).
    time.sleep(0.5)

    # Trigger via SYS. We re-send on every run; main_loop is already exited
    # (we go to BASIC via 'Q' before the first run) so BASIC runs SYS.
    sys_line = f"sys{ROUTINE_ADDR}\r"
    send_text(transport, sys_line)

    # Now poll — but we want the wall-clock to span only the verify call.
    # The stub writes RUN_VALUE->$4540 *before* jsr ecdsa_verify and
    # DONE_VALUE->$4541 *after*. Wait for RUN_VALUE first to start the
    # clock, then wait for DONE_VALUE and stop the clock.

    # Helper: retry read_memory with a short sleep on transient HTTP errors.
    # During long compute runs the U64E's HTTP API occasionally times out or
    # refuses the connection; a short wait + retry is enough to get past it.
    def _robust_read(addr: int, n: int = 1, retries: int = 5) -> int:
        last_exc: Exception | None = None
        for _ in range(retries):
            try:
                return transport.read_memory(addr, n)[0]
            except Exception as exc:
                last_exc = exc
                time.sleep(1.5)
        raise RuntimeError(f"read_memory({addr:#06x}) failed after "
                           f"{retries} retries: {last_exc}")

    # Stage 1: wait for RUN_VALUE
    deadline = time.time() + 30.0   # generous — SYS setup + keyboard
    while time.time() < deadline:
        try:
            b = _robust_read(RUN_SENTINEL)
        except Exception as exc:
            return {"error": f"read_memory failed waiting for RUN: {exc}",
                    "carry": None, "seconds": None}
        if b == RUN_VALUE:
            break
        time.sleep(POLL_S)
    else:
        return {
            "error": "stub never reached RUN_VALUE sentinel",
            "carry": None,
            "seconds": None,
        }

    t0 = time.perf_counter()

    # Stage 2: wait for DONE_VALUE
    deadline = time.time() + timeout_s
    while time.time() < deadline:
        try:
            b = _robust_read(DONE_SENTINEL)
        except Exception as exc:
            return {"error": f"read_memory failed waiting for DONE: {exc}",
                    "carry": None, "seconds": None}
        if b == DONE_VALUE:
            t1 = time.perf_counter()
            break
        time.sleep(POLL_S)
    else:
        # Timeout — dump the progress byte and report.
        try:
            progress = _robust_read(PROGRESS_BYTE)
        except Exception:
            progress = 0xFF
        return {
            "error": f"TIMEOUT after {timeout_s:.0f}s "
                     f"(progress=0x{progress:02X})",
            "carry": None,
            "seconds": None,
        }

    # Carry flag result
    carry_byte = _robust_read(CARRY_BYTE)
    carry_bit = carry_byte & 0x01
    seconds = t1 - t0
    return {
        "carry_byte": carry_byte,
        "carry_bit": int(carry_bit),
        "valid": (carry_bit == 0),
        "seconds": seconds,
    }


def _git_head_sha() -> str:
    try:
        out = subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=str(REPO_ROOT), stderr=subprocess.DEVNULL, timeout=3.0,
        )
        return out.decode("ascii", errors="replace").strip() or "<unknown>"
    except Exception:
        return "<unknown>"


def _create_run_dir(base: Path) -> Path:
    base.mkdir(parents=True, exist_ok=True)
    stamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    cand = base / stamp
    i = 0
    while cand.exists():
        i += 1
        cand = base / f"{stamp}_{i}"
    cand.mkdir(parents=True, exist_ok=False)
    return cand


def _prune_old(base: Path, keep: int = 5) -> None:
    if not base.is_dir():
        return
    entries: list[tuple[float, Path]] = []
    for child in base.iterdir():
        if child.is_dir():
            try:
                entries.append((child.stat().st_mtime, child))
            except OSError:
                pass
    entries.sort(key=lambda t: t[0], reverse=True)
    for _, d in entries[keep:]:
        try:
            shutil.rmtree(d)
        except Exception:
            pass


def _keep_cycle(word: int) -> bool:
    """DebugCapture filter — keep CPU cycles in crypto code or ecdsa data."""
    if not (word >> 31) & 1:
        return False
    addr = word & 0xFFFF
    return (0x6000 <= addr <= 0x9FFF) or (0xB000 <= addr <= 0xB3FF)


def main() -> int:
    if not PRG_PATH.is_file():
        print(f"ERROR: PRG not found at {PRG_PATH}", file=sys.stderr)
        return 2
    if not LABELS_PATH.is_file():
        print(f"ERROR: labels.txt not found", file=sys.stderr)
        return 2
    if not VECTORS_PATH.is_file():
        print(f"ERROR: vectors JSON not found at {VECTORS_PATH}."
              f" Run tools/uci/_ecdsa_vectors.py first.", file=sys.stderr)
        return 2

    labels = _load_labels()
    required = ["ecdsa_verify", "ecdsa_curve_id", "ecdsa_hash",
                "ecdsa_hash_len", "ecdsa_sig_r", "ecdsa_sig_s",
                "ecdsa_sig_len", "ecdsa_pubkey_x", "ecdsa_pubkey_y",
                "net_initialized"]
    missing = [n for n in required if n not in labels]
    if missing:
        print(f"ERROR: missing labels: {missing}", file=sys.stderr)
        return 2

    print(f"ecdsa_verify     = ${labels['ecdsa_verify']:04X}")
    print(f"ecdsa_hash       = ${labels['ecdsa_hash']:04X}")
    print(f"ecdsa_pubkey_x   = ${labels['ecdsa_pubkey_x']:04X}")
    print(f"MHz list         = {MHZ_LIST}")
    print(f"REPEATS_POS      = {REPEATS_POS}")
    print(f"Vectors          = {VECTORS_PATH}")

    vectors = json.loads(VECTORS_PATH.read_text())["vectors"]
    print(f"Loaded {len(vectors)} vectors")

    # --- Memory policy + arbiter: replace the hardcoded $4200-$4543
    # scratch addresses (which silently overlapped X25519_RODATA/BSS
    # under USE_X25519_SIBLING=1) with arbiter-allocated ones derived
    # from build/labels.txt.  The transport is created inside the
    # try-block below; we attach the policy there.
    global ROUTINE_ADDR, RUN_SENTINEL, DONE_SENTINEL
    global CARRY_BYTE, PROGRESS_BYTE
    memory_policy, arbiter = build_policy_and_arbiter(LABELS_PATH, PRG_PATH)
    ROUTINE_ADDR  = arbiter.alloc(320, name="ecdsa_stub")
    RUN_SENTINEL  = arbiter.alloc(1,   name="run_sentinel")
    DONE_SENTINEL = arbiter.alloc(1,   name="done_sentinel")
    CARRY_BYTE    = arbiter.alloc(1,   name="carry_byte")
    PROGRESS_BYTE = arbiter.alloc(1,   name="progress_byte")
    print(
        f"MemoryPolicy reserved {len(memory_policy.reserved_regions)}"
        f" region(s); arbiter allocations:"
    )
    for base, last, note in arbiter.allocations:
        print(f"  ${base:04X}-${last:04X}  {note}")

    stub = _build_stub(labels)
    prg = PRG_PATH.read_bytes()
    run_dir: Path | None = None
    if DEBUG_CAPTURE:
        _prune_old(DEBUG_BASE_DIR, keep=5)
        run_dir = _create_run_dir(DEBUG_BASE_DIR)
        print(f"Debug dir: {run_dir}")

    lock = DeviceLock(HOST)
    if not lock.acquire(timeout=60.0):
        print(f"ERROR: could not acquire DeviceLock({HOST})", file=sys.stderr)
        return 3
    print(f"Acquired DeviceLock({HOST})")

    client: Ultimate64Client | None = None
    uci_enabled = False
    debug_cap: DebugCapture | None = None
    debug_started = False
    results: list[dict] = []

    try:
        client = Ultimate64Client(host=HOST, timeout=60.0)
        transport = Ultimate64Transport(host=HOST, timeout=60.0, client=client)
        # MemoryPolicy guard: any subsequent write_memory(addr, ...)
        # that overlaps a reserved c64-https segment raises before
        # crossing the wire.
        transport.memory_policy = memory_policy

        print("Enabling UCI...")
        enable_uci(client)
        uci_enabled = True

        print("Resetting machine...")
        client.reset()
        time.sleep(2.5)

        print("run_prg(PRG)...")
        client.run_prg(prg)
        # Wait for auto-init (entropy + sqtab + reu_mul + DHCP).
        # reu_mul_init is the slow step; 22s is what test_https_local uses.
        time.sleep(22.0)

        init_flag = transport.read_memory(labels["net_initialized"], 1)[0]
        print(f"net_initialized = ${init_flag:02X}")

        # DMA-write the stub before quitting to BASIC (cleaner timing —
        # we don't want BASIC overwriting $4200+ with variables).
        transport.write_memory(ROUTINE_ADDR, stub)
        # Clear marker bytes
        transport.write_memory(RUN_SENTINEL, bytes([0, 0, 0, 0]))

        # Quit main_loop to BASIC
        print("Sending 'Q' to exit main_loop...")
        send_text(transport, "q\r")
        time.sleep(2.0)

        for mhz in MHZ_LIST:
            print(f"\n========== {mhz} MHz ==========")
            set_turbo_mhz(client, mhz)
            time.sleep(0.5)

            # Per-MHz timeout heuristic
            per_run_timeout = 180.0 if mhz >= 4 else 2400.0

            # --- optional debug capture on the FIRST vector of FIRST speed ---
            first_mhz = (mhz == MHZ_LIST[0])
            for vi, vec in enumerate(vectors):
                reps = REPEATS_POS if vec["expected_valid"] else REPEATS_NEG
                runs: list[dict] = []
                for rep in range(reps):
                    tag = f"{mhz}MHz {vec['name']} rep {rep+1}/{reps}"
                    print(f"  [{tag}] running...", flush=True)

                    # Start debug capture around the first 48 MHz positive run
                    if (DEBUG_CAPTURE and first_mhz
                            and vec["name"] == "pos_rfc6979_sample"
                            and rep == 0 and not debug_started
                            and run_dir is not None):
                        try:
                            set_debug_stream_mode(client, DEBUG_MODE_6510)
                            debug_cap = DebugCapture(
                                port=DEFAULT_DEBUG_PORT,
                                recv_buf_size=1024 * 1024,
                                max_bytes=150 * 1024 * 1024,
                                filter=_keep_cycle,
                            )
                            debug_cap.start()
                            # Bind to dev host LAN IP — the U64 streams to us
                            import socket as _s
                            ss = _s.socket(_s.AF_INET, _s.SOCK_DGRAM)
                            ss.connect((HOST, 80))
                            my_ip = ss.getsockname()[0]
                            ss.close()
                            client.stream_debug_start(
                                f"{my_ip}:{DEFAULT_DEBUG_PORT}")
                            debug_started = True
                            time.sleep(0.3)
                            print(f"    (debug stream started -> "
                                  f"{my_ip}:{DEFAULT_DEBUG_PORT})")
                        except Exception as exc:
                            print(f"    WARNING: debug start failed: {exc}")
                            debug_cap = None

                    out = _run_single(
                        transport, client, labels, vec, mhz,
                        timeout_s=per_run_timeout,
                    )

                    # Stop debug capture after the first positive run
                    if (DEBUG_CAPTURE and debug_started
                            and vec["name"] == "pos_rfc6979_sample"
                            and rep == 0 and debug_cap is not None):
                        try:
                            client.stream_debug_stop()
                            cap_result = debug_cap.stop()
                            # Minimal summary: packets + cycles + bytes
                            total = len(getattr(cap_result, "trace", []))
                            pkts = getattr(cap_result, "packets_received", 0)
                            drop = getattr(cap_result, "packets_dropped", 0)
                            dur = getattr(cap_result, "duration_seconds", 0.0)
                            print(f"    debug capture stopped: "
                                  f"{pkts} pkts, {drop} drop, "
                                  f"{total} cycles, {dur:.1f}s")
                            if run_dir is not None:
                                # Pack to trace.bin for post-mortem
                                try:
                                    trace = getattr(cap_result, "trace", None) or []
                                    count = len(trace)
                                    fmt = f"<{count}I"
                                    buf = struct.pack(
                                        fmt,
                                        *(int(c.raw) & 0xFFFFFFFF
                                          for c in trace),
                                    )
                                    (run_dir / "trace.bin").write_bytes(buf)
                                    (run_dir / "trace.bin.meta.json").write_text(
                                        json.dumps({
                                            "format": "packed-u32-le",
                                            "cycle_count": count,
                                            "duration_seconds": dur,
                                            "packets_received": pkts,
                                            "packets_dropped": drop,
                                            "filter": ("CPU cycles with "
                                                       "PC in $6000-$9FFF "
                                                       "or ecdsa buffer "
                                                       "$B000-$B3FF"),
                                            "speed_mhz": mhz,
                                            "vector": vec["name"],
                                        }, indent=2),
                                    )
                                    print(f"    trace.bin -> "
                                          f"{run_dir / 'trace.bin'} "
                                          f"({len(buf)} bytes)")
                                except Exception as exc:
                                    print(f"    WARNING: trace pack failed: {exc}")
                        except Exception as exc:
                            print(f"    WARNING: debug stop failed: {exc}")
                        finally:
                            debug_started = False

                    if "error" in out:
                        print(f"    ERROR: {out['error']}")
                    else:
                        ok = (out["valid"] == vec["expected_valid"])
                        tag = "OK" if ok else "FAIL"
                        print(f"    {tag}  valid={out['valid']} "
                              f"(expected {vec['expected_valid']}) "
                              f"wall={out['seconds']:.3f}s "
                              f"carry_byte=${out['carry_byte']:02X}")
                    out.update(dict(
                        mhz=mhz,
                        vector=vec["name"],
                        expected_valid=vec["expected_valid"],
                        rep=rep + 1,
                        reps=reps,
                    ))
                    runs.append(out)
                results.append({
                    "mhz": mhz,
                    "vector": vec["name"],
                    "expected_valid": vec["expected_valid"],
                    "runs": runs,
                })

        # --- Aggregated summary ---
        print("\n\n================ SUMMARY ================\n")
        all_pass = True
        for group in results:
            runs = group["runs"]
            times = [r["seconds"] for r in runs
                     if r.get("seconds") is not None]
            correctness = [(r.get("valid") == group["expected_valid"])
                           for r in runs if "valid" in r]
            if not times:
                print(f"  {group['mhz']:>3d} MHz  {group['vector']:<22s}  "
                      f"NO TIMING — errors: "
                      f"{[r.get('error') for r in runs]}")
                all_pass = False
                continue
            tmin = min(times); tmed = sorted(times)[len(times)//2]
            tmax = max(times)
            c_ok = all(correctness) and len(correctness) == len(runs)
            print(f"  {group['mhz']:>3d} MHz  {group['vector']:<22s}  "
                  f"expect={group['expected_valid']!s:<5s}  "
                  f"n={len(times)}  "
                  f"min={tmin:7.3f}s  med={tmed:7.3f}s  max={tmax:7.3f}s  "
                  f"correctness={'PASS' if c_ok else 'FAIL'}")
            if not c_ok:
                all_pass = False

        report_path = None
        if run_dir is not None:
            report_path = run_dir / "results.json"
        else:
            out_base = Path("/tmp/ecdsa_debug")
            out_base.mkdir(parents=True, exist_ok=True)
            report_path = out_base / (
                "bench_ecdsa_"
                + datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
                + ".json"
            )
        report_path.write_text(json.dumps({
            "git_head": _git_head_sha(),
            "host": HOST,
            "vectors_file": str(VECTORS_PATH),
            "results": results,
        }, indent=2, default=str))
        print(f"\nJSON results -> {report_path}")

        return 0 if all_pass else 1

    finally:
        # Ensure debug stream is stopped if we bailed early
        if debug_started and client is not None:
            try:
                client.stream_debug_stop()
            except Exception:
                pass
        if debug_cap is not None:
            try:
                debug_cap.stop()
            except Exception:
                pass
        if uci_enabled and client is not None:
            print("\nDisabling UCI...")
            try:
                disable_uci(client)
            except Exception as exc:
                print(f"WARNING: disable_uci failed: {exc}")
        lock.release()
        print(f"Released DeviceLock({HOST})")


if __name__ == "__main__":
    raise SystemExit(main())
