#!/usr/bin/env python3
"""Self-contained TLS 1.3 test listener for the c64-https client.

This is a stand-alone clone of the inline HTTPS listener in the c64-https
repo's ``tools/uci/test_https_local.py``. It stands up the entire server
side of the end-to-end test — including generating its own certificate —
with no dependency on the c64-https repo or the c64-test-harness package.

Behavior cloned verbatim from the reference listener (do NOT "improve" the
protocol; the C64 client parses a fixed shape):

  * TLS 1.3 ONLY (``ssl.PROTOCOL_TLS_SERVER`` pinned min = max = TLSv1_3).
    The C64 advertises a single cipher suite,
    TLS_CHACHA20_POLY1305_SHA256 (0x1303); the stdlib server offers it
    among its TLS 1.3 defaults and picks it.
  * ECDSA P-256 leaf cert (auto-generated by gen_certs.py if ./certs is
    missing). The C64 verifies the CertificateVerify signature against the
    leaf key, so a fresh self-signed P-256 cert works.
  * Reads one request, then sends this EXACT response (the C64's HTTP
    parser needs a 3-digit status and "Content-Length: " with a single
    space after the colon):

        HTTP/1.0 200 OK\\r\\n
        Content-Length: 21\\r\\n
        \\r\\n
        HELLO FROM TLS SERVER

  * Single connection then exit (matches the reference; loops with --serve-forever).
  * Writes server_result.json with the same schema the reference harness
    emits (listening / client_addr / request / error).

Environment / CLI:
  HTTPS_PORT env or --port   listener port. Default 443, auto-falls back to
                             4433 if the privileged bind fails (clones the
                             reference default + fallback).
  --bind                     bind address (default 0.0.0.0 so the C64 on the
                             LAN can reach it; the reference binds the dev
                             host's LAN IP).
  --cert / --key             cert + key paths (default ./certs/server.{pem,key}).
  --result                   server_result.json path (default ./server_result.json).
  --accept-timeout           accept + per-connection timeout seconds (default 600).
  --serve-forever            keep accepting connections instead of exiting
                             after the first (convenience; off by default to
                             match the reference one-shot behavior).
"""
from __future__ import annotations

import argparse
import base64
import json
import os
import socket
import ssl
import sys
import time
import traceback
from pathlib import Path

HERE = Path(__file__).resolve().parent

# --- Canonical response bytes (cloned verbatim from test_https_local.py) ---
EXPECTED_BODY = "HELLO FROM TLS SERVER"
HTTP_RESPONSE = (
    b"HTTP/1.0 200 OK\r\n"
    b"Content-Length: 21\r\n"
    b"\r\n"
    b"HELLO FROM TLS SERVER"
)

DEFAULT_PORT = int(os.environ.get("HTTPS_PORT", "443"))
FALLBACK_PORT = 4433


def _ensure_certs(cert_path: Path, key_path: Path) -> None:
    """Auto-generate a P-256 cert/key pair if either file is missing."""
    if cert_path.is_file() and key_path.is_file():
        return
    print(f"cert/key missing ({cert_path} / {key_path}); generating...")
    # Import lazily so `listener.py --help` works without cryptography.
    import gen_certs
    gen_certs.generate(
        cn="www.foo.bar",
        sans=["foo.bar", "www.foo.bar"],
        out_dir=cert_path.parent,
        force=False,
    )


def _make_ssl_context(cert_path: Path, key_path: Path) -> ssl.SSLContext:
    """TLS 1.3-only server context (cloned from the reference listener).

    The C64 speaks TLS 1.3 exclusively, so a Python whose ``ssl`` module
    lacks TLS 1.3 (e.g. macOS system Python, linked against LibreSSL 2.x)
    cannot serve this client. Detect that up front and fail with a clear
    message instead of a cryptic ValueError deep in the handshake setup.
    """
    if not getattr(ssl, "HAS_TLSv1_3", False):
        raise SystemExit(
            "ERROR: this Python's ssl module has no TLS 1.3 support "
            f"({ssl.OPENSSL_VERSION}). The C64 client requires TLS 1.3.\n"
            "Use a Python linked against OpenSSL 1.1.1+ / 3.x (most Linux "
            "distros ship this; on macOS the system python3 uses LibreSSL "
            "and will not work — install python3 from python.org or "
            "Homebrew)."
        )
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    ctx.load_cert_chain(certfile=str(cert_path), keyfile=str(key_path))
    try:
        ctx.minimum_version = ssl.TLSVersion.TLSv1_3
        ctx.maximum_version = ssl.TLSVersion.TLSv1_3
    except (AttributeError, ValueError):
        pass
    return ctx


def _try_bind(bind_ip: str, port: int) -> socket.socket | None:
    srv = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    srv.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    try:
        srv.bind((bind_ip, port))
    except (PermissionError, OSError):
        srv.close()
        return None
    return srv


def _serialize_result(result: dict, path: Path) -> None:
    """Write server_result.json using the reference harness schema.

    Bytes fields become {"__type__": "bytes-b64", "b64": ..., "len": ...};
    tuples become lists; exceptions are captured as type/str/traceback.
    Matches _serialize_server_result() in test_https_local.py.
    """
    out: dict = {}
    for key, val in result.items():
        if isinstance(val, (bytes, bytearray)):
            out[key] = {
                "__type__": "bytes-b64",
                "b64": base64.b64encode(bytes(val)).decode("ascii"),
                "len": len(val),
            }
        elif isinstance(val, BaseException):
            out[key] = {
                "__type__": "exception",
                "class": type(val).__name__,
                "str": str(val),
                "traceback": traceback.format_exception(
                    type(val), val, val.__traceback__),
            }
        elif isinstance(val, tuple):
            out[key] = list(val)
        else:
            try:
                json.dumps(val)
                out[key] = val
            except TypeError:
                out[key] = repr(val)
    path.write_text(json.dumps(out, indent=2, default=str))


def _handle_one(srv: socket.socket, ctx: ssl.SSLContext,
                accept_timeout: float, result: dict) -> None:
    """Accept one connection, handshake, serve the canonical response.

    Mirrors _run_https_server() in test_https_local.py: the result dict is
    populated with listening / client_addr / request / error as it goes.
    """
    srv.settimeout(accept_timeout)
    raw_conn, addr = srv.accept()
    result["client_addr"] = addr
    print(f"connection from {addr[0]}:{addr[1]}")
    try:
        tls_conn = ctx.wrap_socket(raw_conn, server_side=True)
    except (ssl.SSLError, OSError) as exc:
        result["error"] = f"TLS handshake failed: {type(exc).__name__}: {exc}"
        print(f"  handshake FAILED: {result['error']}")
        try:
            raw_conn.close()
        except Exception:
            pass
        return

    ver = tls_conn.version()
    suite = tls_conn.cipher()
    result["tls_version"] = ver
    result["cipher"] = suite[0] if suite else None
    print(f"  handshake OK: {ver} / {suite[0] if suite else '?'}")
    try:
        tls_conn.settimeout(accept_timeout)
        try:
            req = tls_conn.recv(1024)
            result["request"] = req
            print(f"  request ({len(req)} B): {req[:80]!r}")
        except socket.timeout:
            result["request"] = b"<timeout>"
            print("  request read TIMED OUT")
        tls_conn.sendall(HTTP_RESPONSE)
        result["response_sent"] = True
        print(f"  served {len(HTTP_RESPONSE)} B "
              f"(body {EXPECTED_BODY!r})")
        # Keep alive briefly for the C64 to drain before FIN (clone).
        time.sleep(1.0)
    finally:
        try:
            tls_conn.unwrap()
        except Exception:
            pass
        try:
            tls_conn.close()
        except Exception:
            pass


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        description="TLS 1.3 test listener for the c64-https client.")
    p.add_argument("--port", type=int, default=DEFAULT_PORT,
                   help=f"listener port (default {DEFAULT_PORT}; "
                        f"auto-falls back to {FALLBACK_PORT})")
    p.add_argument("--bind", default="0.0.0.0",
                   help="bind address (default 0.0.0.0)")
    p.add_argument("--cert", default=str(HERE / "certs" / "server.pem"),
                   help="server cert PEM (default ./certs/server.pem)")
    p.add_argument("--key", default=str(HERE / "certs" / "server.key"),
                   help="server key PEM (default ./certs/server.key)")
    p.add_argument("--result", default=str(HERE / "server_result.json"),
                   help="server_result.json path (default ./server_result.json)")
    p.add_argument("--accept-timeout", type=float, default=600.0,
                   help="accept + per-connection timeout seconds (default 600)")
    p.add_argument("--serve-forever", action="store_true",
                   help="keep serving after the first connection")
    args = p.parse_args(argv)

    cert_path = Path(args.cert)
    key_path = Path(args.key)
    result_path = Path(args.result)

    _ensure_certs(cert_path, key_path)
    ctx = _make_ssl_context(cert_path, key_path)

    # Bind: try requested port, fall back to 4433 on privileged-bind failure
    # (clones the reference listener's 443 -> 4433 fallback).
    srv = _try_bind(args.bind, args.port)
    chosen_port = args.port
    if srv is None and args.port != FALLBACK_PORT:
        print(f"bind {args.bind}:{args.port} failed (need root?); "
              f"falling back to {FALLBACK_PORT}")
        srv = _try_bind(args.bind, FALLBACK_PORT)
        chosen_port = FALLBACK_PORT
    if srv is None:
        print(f"ERROR: could not bind {args.bind}:{args.port}", file=sys.stderr)
        return 1

    srv.listen(1)
    print(f"TLS 1.3 listener up on {args.bind}:{chosen_port}")
    print(f"  cert : {cert_path}")
    print(f"  body : {EXPECTED_BODY!r}")
    print(f"Point the C64 client / test at this host on port {chosen_port}.")

    result: dict = {"listening": True, "port": chosen_port}
    exit_code = 0
    try:
        while True:
            conn_result: dict = {"listening": True, "port": chosen_port}
            try:
                _handle_one(srv, ctx, args.accept_timeout, conn_result)
            except socket.timeout:
                conn_result["error"] = "accept timed out"
                print("accept timed out")
                exit_code = 1
            except Exception as exc:
                conn_result["error"] = f"{type(exc).__name__}: {exc}"
                print(f"ERROR: {conn_result['error']}", file=sys.stderr)
                exit_code = 1
            result = conn_result
            _serialize_result(result, result_path)
            print(f"wrote {result_path}")
            if not args.serve_forever:
                break
    except KeyboardInterrupt:
        print("\ninterrupted")
    finally:
        try:
            srv.close()
        except Exception:
            pass
    return exit_code


if __name__ == "__main__":
    sys.exit(main())
