#!/usr/bin/env python3
"""Build dist/c64-https-listener.py — the single-file, self-extracting
TLS 1.3 test listener.

Packs the sources under tools/package/listener/ into one runnable .py: a small
bootstrap header followed by a base64+zlib tar of the modules, which unpacks
into a temp dir and runs. One file, `python3 c64-https-listener.py`, done.

WHAT HAPPENED TO THE DEPENDENCY
-------------------------------
The obvious blocker for a self-extracting Python bundle is that `cryptography`
is a compiled extension — wheels are per-platform and per-Python-version, so
it cannot be embedded in a source payload and stay portable. The options were:
embed the pure-Python parts and error out asking for `pip install
cryptography`; vendor a pure-Python TLS stack; or bootstrap a venv on first
run.

None of those were taken, because the premise was wrong. `cryptography` was
never needed for TLS here — the server has always been stdlib `ssl`. It was
needed for exactly one thing: minting the self-signed P-256 certificate. So
gen_certs.py now does that in pure Python (~200 lines: P-256 point
arithmetic, a minimal DER encoder, ECDSA-SHA256), and the bundle has **no
third-party dependency at all**. Nothing to pip install, no venv, no network.

What remains is a requirement on the *interpreter*, not on a package: an `ssl`
module with TLS 1.3, i.e. linked against OpenSSL 1.1.1+. macOS's system
python3 is LibreSSL 2.8.3 and cannot serve TLS 1.3 at any price. That is
detected up front and reported in one line, never as a traceback, and it is
stated in the manifest so nobody has to discover it by running the thing.

DETERMINISM
-----------
Tar metadata is pinned (mtime 0, uid/gid 0, mode 0644, USTAR) and zlib level 9
is deterministic, so the same sources produce a byte-identical bundle. That
lets the manifest's sha256 mean something.

Usage:  tools/package/build_listener.py [--out PATH] [--selftest]
        --selftest additionally runs the built bundle's own --selftest.
"""
from __future__ import annotations

import argparse
import base64
import hashlib
import io
import subprocess
import sys
import tarfile
import zlib
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC_DIR = HERE / "listener"
REPO_ROOT = HERE.parent.parent

# Modules that go into the bundle. Nothing else from the tree leaks in.
PAYLOAD_FILES = ["listener.py", "gen_certs.py", "README.md"]
ENTRY = "listener.py"

BOOTSTRAP = '''#!/usr/bin/env python3
"""c64-https TLS 1.3 test listener — single file, no dependencies.

Stands up the entire server side of the c64-https end-to-end test: mints a
fresh self-signed ECDSA P-256 certificate, serves TLS 1.3 only, and returns
the canonical response the Commodore 64 client expects.

    python3 c64-https-listener.py                 # port 443, falls back to 4433
    python3 c64-https-listener.py --port 4433     # unprivileged
    python3 c64-https-listener.py --selftest      # prove it works, no C64 needed
    python3 c64-https-listener.py --extract DIR   # unpack the sources and exit
    python3 c64-https-listener.py --help

REQUIREMENTS: Python 3.8+ whose ssl module has TLS 1.3 (OpenSSL 1.1.1+ or
3.x). There is nothing to pip install. macOS's /usr/bin/python3 is linked
against LibreSSL 2.8.3, has no TLS 1.3, and will refuse with a one-line
message — use python.org or Homebrew python3 there.

This file is generated by tools/package/build_listener.py in the c64-https
repo; edit the sources there, not the payload below.

The certificate it generates is a throwaway test fixture, not a trust anchor.
Do not deploy this anywhere real.
"""
import atexit
import base64
import hashlib
import io
import os
import runpy
import shutil
import sys
import tarfile
import tempfile
import zlib

_PAYLOAD_SHA256 = "@SHA256@"
_ENTRY = "@ENTRY@"
_PAYLOAD = """\\
@PAYLOAD@"""


def _die(msg):
    sys.stderr.write("ERROR: %s\\n" % msg)
    raise SystemExit(1)


def _unpack(dest):
    raw = base64.b64decode(_PAYLOAD)
    got = hashlib.sha256(raw).hexdigest()
    if got != _PAYLOAD_SHA256:
        _die("this file's embedded payload is corrupt (sha256 %s, expected "
             "%s) — re-download it" % (got[:16], _PAYLOAD_SHA256[:16]))
    with tarfile.open(fileobj=io.BytesIO(zlib.decompress(raw)), mode="r:") as tar:
        # Every member is a plain file written by build_listener.py; reject
        # anything else rather than trusting the archive.
        for member in tar.getmembers():
            if not member.isfile() or "/" in member.name or member.name.startswith("."):
                _die("unexpected payload member %r" % member.name)
        # filter="data" is the 3.12+ safe extraction mode and the default from
        # 3.14; passing it unconditionally there and omitting it below keeps
        # one file working across 3.8 -> 3.14 without a DeprecationWarning.
        if sys.version_info >= (3, 12):
            tar.extractall(dest, filter="data")
        else:
            tar.extractall(dest)


def _main():
    if sys.version_info < (3, 8):
        _die("needs Python 3.8+, this is %d.%d"
             % (sys.version_info[0], sys.version_info[1]))

    argv = sys.argv[1:]
    if "--extract" in argv:
        i = argv.index("--extract")
        if i + 1 >= len(argv):
            _die("--extract needs a directory")
        dest = os.path.abspath(argv[i + 1])
        os.makedirs(dest, exist_ok=True)
        _unpack(dest)
        print("extracted %d files to %s" % (len(os.listdir(dest)), dest))
        return 0

    tmp = tempfile.mkdtemp(prefix="c64-https-listener-")
    atexit.register(shutil.rmtree, tmp, True)
    _unpack(tmp)
    sys.path.insert(0, tmp)
    # run_path with run_name="__main__" makes the extracted module run its own
    # __main__ block, which raises SystemExit with the real exit code.
    runpy.run_path(os.path.join(tmp, _ENTRY), run_name="__main__")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(_main())
    except SystemExit:
        raise
    except KeyboardInterrupt:
        sys.exit(130)
    except Exception as exc:
        _die("%s: %s" % (type(exc).__name__, exc))
'''


def build(out_path: Path) -> Path:
    missing = [f for f in PAYLOAD_FILES if not (SRC_DIR / f).is_file()]
    if missing:
        raise SystemExit(f"ERROR: missing listener sources: {missing}")

    buf = io.BytesIO()
    with tarfile.open(fileobj=buf, mode="w",
                      format=tarfile.USTAR_FORMAT) as tar:
        for name in PAYLOAD_FILES:
            data = (SRC_DIR / name).read_bytes()
            info = tarfile.TarInfo(name)
            info.size = len(data)
            # Pinned metadata: without this the bundle's sha256 would change
            # every time a source file's mtime did, and the manifest checksum
            # would stop being reproducible.
            info.mtime = 0
            info.mode = 0o644
            info.uid = info.gid = 0
            info.uname = info.gname = ""
            tar.addfile(info, io.BytesIO(data))

    compressed = zlib.compress(buf.getvalue(), 9)
    digest = hashlib.sha256(compressed).hexdigest()
    b64 = base64.b64encode(compressed).decode("ascii")
    lines = "\n".join(b64[i:i + 76] for i in range(0, len(b64), 76))

    text = (BOOTSTRAP
            .replace("@SHA256@", digest)
            .replace("@ENTRY@", ENTRY)
            .replace("@PAYLOAD@", lines))
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(text)
    out_path.chmod(0o755)
    print(f"[package] wrote {out_path}")
    print(f"[package]   {out_path.stat().st_size} bytes, "
          f"{len(PAYLOAD_FILES)} embedded modules, payload sha256 {digest}")
    return out_path


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--out", default=str(REPO_ROOT / "dist" / "c64-https-listener.py"),
                   help="output path (default dist/c64-https-listener.py)")
    p.add_argument("--selftest", action="store_true",
                   help="run the built bundle's own --selftest afterwards")
    args = p.parse_args(argv)

    out = build(Path(args.out))
    if args.selftest:
        print(f"[package] running {out.name} --selftest")
        rc = subprocess.call([sys.executable, str(out), "--selftest"])
        if rc != 0:
            print(f"[package] bundle selftest FAILED (exit {rc})", file=sys.stderr)
            return rc
    return 0


if __name__ == "__main__":
    sys.exit(main())
