#!/usr/bin/env bash
# =============================================================================
# tools/package/build_prgs.sh — build the release PRG matrix into dist/.
#
# Four variants, every combination of networking backend x crypto profile:
#
#   c64-https-uci-reu.prg      make BACKEND=uci
#   c64-https-uci-onchip.prg   make BACKEND=uci USE_NISTCURVES_ONCHIP=1
#   c64-https-ip65-reu.prg     make BACKEND=ip65
#   c64-https-ip65-onchip.prg  make BACKEND=ip65 USE_NISTCURVES_ONCHIP=1
#
# The matrix itself lives in _common.sh; this script has no per-variant
# knowledge and nothing version-specific, so it survives a library bump with
# zero edits.
#
# TWO TRAPS this script exists to avoid, both observed in this repo:
#
#   1. `make clean` runs before EVERY variant. `BACKEND=` is not a -D flag, it
#      selects an include path, and make's dependency graph cannot see it.
#      Skipping the clean yields either a mixed binary at exactly the right
#      size, or (macOS GNU Make 3.81, 1-second mtime resolution) no relink at
#      all, leaving the *other* variant's PRG in place. Exit 0 either way.
#   2. Every build is checked by PRG sha256, recorded in dist/build-info.txt.
#      Object hashes are worthless as evidence — ca65 stamps wall-clock time
#      into every .o header — but ld65 does not propagate it, so the PRG is
#      deterministic and comparable.
#
# Also bootstraps the ip65 blob (`ip65-build/ip65-c64.bin`), which is a
# gitignored artifact a plain `make` will NOT build: a fresh clone dies in the
# ca65 `.incbin` before any link.
#
# Writes dist/build-info.txt (git HEAD, submodule pins, per-variant args/size/
# sha256). write_manifest.sh consumes it.
#
# Usage:  tools/package/build_prgs.sh
# =============================================================================
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$PROJECT_ROOT"
# shellcheck source=tools/package/_common.sh
. "$PROJECT_ROOT/tools/package/_common.sh"

mkdir -p "$DIST"

GIT_HEAD="$(git rev-parse HEAD)"
GIT_HEAD_SHORT="$(git rev-parse --short HEAD)"
GIT_DIRTY=""
git diff --quiet HEAD -- 2>/dev/null || GIT_DIRTY=" (working tree DIRTY)"

# --- ip65 blob bootstrap ------------------------------------------------------
IP65_BIN="$PROJECT_ROOT/ip65-build/ip65-c64.bin"
if [ ! -f "$IP65_BIN" ]; then
    echo "[package] ip65 blob absent — bootstrapping (make ip65-libs && make ip65-blob)"
    if [ ! -e "$PROJECT_ROOT/ip65/Makefile" ]; then
        echo "ERROR: ip65 submodule not checked out. Run:" >&2
        echo "         git submodule update --init --recursive" >&2
        exit 1
    fi
    make ip65-libs >/dev/null
    make ip65-blob >/dev/null
    echo "[package] ip65 blob built: $(wc -c < "$IP65_BIN" | tr -d ' ') bytes, $(sha256_of "$IP65_BIN")"
fi

# --- Fresh build-info ---------------------------------------------------------
{
    echo "# c64-https release build info"
    echo "# generated by tools/package/build_prgs.sh"
    echo "generated=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "git_head=$GIT_HEAD"
    echo "git_head_short=$GIT_HEAD_SHORT"
    echo "git_dirty=$([ -n "$GIT_DIRTY" ] && echo yes || echo no)"
    echo "ip65_blob_sha256=$(sha256_of "$IP65_BIN")"
    echo "ip65_blob_bytes=$(wc -c < "$IP65_BIN" | tr -d ' ')"
    submodule_pins | while read -r sub sha tag; do
        echo "submodule=$sub $sha $tag"
    done
} > "$BUILD_INFO"

# --- Build every variant ------------------------------------------------------
echo "[package] HEAD $GIT_HEAD_SHORT$GIT_DIRTY"
failed=0
for line in "${PACKAGE_VARIANTS[@]}"; do
    key="$(variant_field "$line" 1)"
    prg="$(variant_field "$line" 2)"
    args="$(variant_field "$line" 3)"

    echo "[package] === $key ==="
    echo "[package] make clean && make $args"
    make clean >/dev/null
    log="$DIST/build-$key.log"
    # Word-splitting $args is intentional — it is a make argument list.
    # shellcheck disable=SC2086
    if ! make $args >"$log" 2>&1; then
        echo "[package] BUILD FAILED for $key — see $log" >&2
        tail -n 15 "$log" >&2
        echo "variant=$key prg=$prg args=$args result=FAILED log=$(basename "$log")" \
            >> "$BUILD_INFO"
        failed=1
        continue
    fi
    if [ ! -f "$BUILT_PRG" ]; then
        echo "[package] ERROR: make $args exited 0 but $BUILT_PRG is missing" >&2
        failed=1
        continue
    fi
    cp "$BUILT_PRG" "$DIST/$prg"
    rm -f "$log"
    bytes="$(wc -c < "$DIST/$prg" | tr -d ' ')"
    sha="$(sha256_of "$DIST/$prg")"
    echo "variant=$key prg=$prg args=$args result=OK bytes=$bytes sha256=$sha" \
        >> "$BUILD_INFO"
    printf '[package] wrote dist/%s  %s bytes  %s\n' "$prg" "$bytes" "$sha"
done

if [ "$failed" -ne 0 ]; then
    echo "[package] PRG matrix INCOMPLETE — at least one variant failed to build." >&2
    exit 1
fi
echo "[package] PRG matrix complete (${#PACKAGE_VARIANTS[@]} variants)."
