#!/usr/bin/env python3
"""Pin where the UCI SYS-trampoline rigs put their C64 scratch (#209, #247).

Every tools/uci script that allocates C64 scratch now takes it from low RAM
(page 3, plus $02A7-$02FF for the ones that outgrow it), never from a tail
of a linked region, and each one is run to its DeviceLock on all five UCI
profiles (tools/rig_scratch_profiles.json: labels captured from real links,
regenerated by ``--build --write-fixtures``). The six rigs that still
carved a tail died in ``MemoryArbiter.alloc`` on master's uci-comb image
(PRG ``3eb16622…``) and on both comb TRUST_STORE=1 images, once #266's cold
bank took most of what was left of the CRYPTO_OVERLAY tail.

``rig_https_local`` (and the two wrappers that run its ``main()``),
``rig_https_live`` and ``rig_https_bad_finished`` used to carve 387 B of
scratch out of whatever tail of a linked region was left — on the shipped
``uci-comb`` product that is the ~126 B CRYPTO_OVERLAY tail, so the rigs
died in ``MemoryArbiter.alloc`` before touching the device, and the fastest
product had no offline handshake rig at all. They now allocate from page 3
($0334-$03FF, ``_memory_policy.LOW_RAM_SCRATCH``), sized to what is
actually written.

No VICE, no hardware, no build: the labels file is a fixture carrying the
segment markers of a real ``BACKEND=uci USE_NISTCURVES_ONCHIP_COMB=1`` link
(PRG sha256 ``638529b5…`` at master ``eed451b``), plus the handful of
symbols the rigs look up. Each rig's ``main()`` is RUN against it, with
every device call faked, up to the DeviceLock — which is exactly where the
old allocation died. On the pre-fix rigs these tests fail with
``MemoryArbiterError``.

    python3 tools/test_rig_scratch.py
    python3 tools/test_rig_scratch.py --build    # also against fresh links
"""

from __future__ import annotations

import ast
import contextlib
import hashlib
import importlib
import io
import json
import re
import ssl
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
UCI = REPO / "tools" / "uci"
for p in (str(UCI), str(REPO / "tools")):
    if p not in sys.path:
        sys.path.insert(0, p)

import _memory_policy as mp  # noqa: E402

#: Segment markers from a real uci-comb link (see module docstring). The
#: CRYPTO_OVERLAY tail here is what the old allocation could not fit in.
COMB_SEGMENTS = """\
al C:0000 .__UCI_BSS_REGION_SIZE__
al C:001E .__ZP_CRYPTO_SIZE__
al C:0022 .__ZP_CRYPTO_LAST__
al C:0022 .__ZP_CRYPTO_START__
al C:0040 .__ZP_WIDE_LAST__
al C:0040 .__ZP_WIDE_SIZE__
al C:0040 .__ZP_WIDE_START__
al C:069A .__NET_BSS_TAIL_SIZE__
al C:0801 .__LOADER_START__
al C:17FF .__LOADER_SIZE__
al C:1B66 .__NET_CODE_SIZE__
al C:1E00 .__CRYPTO_OVERLAY_SIZE__
al C:1E00 .__OVERLAY_BLOB_CURVE_RAM_SIZE__
al C:1F75 .__LOADER_LAST__
al C:2000 .__CRYPTO_COLD_SHADOW_SIZE__
al C:2000 .__NET_CODE_START__
al C:2000 .__OVERLAY_FILE_PAD_SIZE__
al C:3AB6 .__NET_CODE_LAST__
al C:3B66 .__NET_BSS_TAIL_START__
al C:4000 .__CRYPTO_HOT_SIZE__
al C:4000 .__UCI_BSS_REGION_LAST__
al C:4000 .__UCI_BSS_REGION_START__
al C:41D5 .__NET_BSS_TAIL_LAST__
al C:4200 .__CRYPTO_OVERLAY_START__
al C:5F92 .__CRYPTO_OVERLAY_LAST__
al C:6000 .__CRYPTO_HOT_START__
al C:9FBC .__CRYPTO_HOT_LAST__
al C:A000 .__CRYPTO_COLD_SHADOW_START__
al C:C000 .__CRYPTO_COLD_SHADOW_LAST__
al C:C000 .__OVERLAY_FILE_PAD_LAST__
al C:C000 .__OVERLAY_FILE_PAD_START__
al C:E000 .__OVERLAY_BLOB_CURVE_RAM_LAST__
al C:E000 .__OVERLAY_BLOB_CURVE_RAM_START__
al C:0F5C .http_get
al C:A526 .http_host_ptr
al C:A528 .http_host_len
al C:A529 .http_path_ptr
al C:A52B .http_path_len
al C:4870 .http_port
al C:2000 .net_init
al C:A227 .net_initialized
al C:610C .uci_socket_id
al C:B3BF .net_last_error
al C:B3C0 .net_tcp_state
al C:A244 .tcp_recv_head
al C:A246 .tcp_recv_tail
al C:611B .uci_req_len
al C:6117 .uci_read_hdr
al C:A630 .http_resp_buf
al C:A830 .http_resp_len
al C:A52C .http_status
al C:A24D .tls_state
al C:A24E .tls_last_state
al C:A24F .tls_reached_connected
al C:0004 .LIB_NISTCURVES_REU_BANKS_USED
al C:9BEB .ec_precompute_256
"""


class _AtLock(Exception):
    """main() reached the DeviceLock: every allocation before it succeeded."""


def _declared_regions(labels: Path):
    return mp._parse_segment_bounds(labels)


def _run_to_lock(modname: str, labels_text: str | None = None):
    """Run a rig's main() on a labels fixture up to acquire_device_lock.

    ``labels_text`` defaults to the #209 comb fixture above.
    -> (reached_lock: bool, allocations, error text, declared regions)
    """
    mod = importlib.import_module(modname)
    arbiters: list = []
    saved = {}

    def patch(name, value):
        if hasattr(mod, name) and name not in saved:
            saved[name] = getattr(mod, name)
            setattr(mod, name, value)

    def record(fn):
        def wrapped(*a, **k):
            policy, arb = fn(*a, **k)
            arbiters.append(arb)
            return policy, arb
        return wrapped

    def at_lock(lock, **k):
        raise _AtLock

    orig_bind = getattr(mod, "_try_bind", None)
    out = io.StringIO()
    reached, err = False, ""
    with tempfile.TemporaryDirectory() as td:
        tmp = Path(td)
        labels = tmp / "labels.txt"
        labels.write_text(COMB_SEGMENTS if labels_text is None
                          else labels_text)
        prg = tmp / "c64-https.prg"
        prg.write_bytes(b"\x01\x08" + bytes(64))
        for name in list(vars(mod)):
            if name.startswith("build_policy_and_"):
                patch(name, record(getattr(mod, name)))
        patch("PRG_PATH", prg)
        patch("LABELS_PATH", labels)
        patch("acquire_device_lock", at_lock)
        patch("enforce_sni_precondition", lambda *a, **k: None)
        patch("_ensure_certs_or_fail", lambda: 0)
        patch("_ensure_certs_p256", lambda: ("cert.pem", "key.pem"))
        patch("_detect_local_ip", lambda h: "127.0.0.1")
        patch("_make_ssl_context",
              lambda: ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER))
        patch("ACCEPT_TIMEOUT", 0.2)
        # rig_https_wiki: trampoline mode is the one that allocates.
        patch("MENU_MODE", False)
        # rig_trust_store: the fake PRG carries no store path to read.
        if hasattr(mod, "TEST_DIR"):
            patch("image_store_path", lambda prg, L: mod.TEST_DIR + "/TRUST.")
        if orig_bind is not None:
            patch("_try_bind", lambda ip, port: orig_bind("127.0.0.1", 0))
        try:
            with contextlib.redirect_stdout(out), \
                    contextlib.redirect_stderr(out):
                mod.main()
        except _AtLock:
            reached = True
        except Exception as exc:                          # noqa: BLE001
            err = f"{type(exc).__name__}: {exc}"
        finally:
            for k, v in saved.items():
                setattr(mod, k, v)
        regions = _declared_regions(labels)
    allocs = [a for arb in arbiters for a in arb.allocations]
    return reached, allocs, err or out.getvalue()[-600:], regions


def _assert_rig_fits_on_comb(modname: str) -> None:
    reached, allocs, err, regions = _run_to_lock(modname)
    assert reached, (f"{modname} could not allocate its scratch on the "
                     f"uci-comb layout (#209): {err}")
    lo, hi = mp.LOW_RAM_SCRATCH
    assert allocs, "no allocation was made"
    for start, last, name in allocs:
        assert lo <= start <= last <= hi, (
            f"{name} ${start:04X}-${last:04X} is outside page-3 scratch "
            f"${lo:04X}-${hi:04X}; it moves with the link again")
        for rname, (rs, re_) in regions.items():
            if rname in mp._SKIP_REGIONS:
                continue
            assert last < rs or start >= re_, (
                f"{name} overlaps declared region {rname}")
    spans = sorted((s, l) for s, l, _ in allocs)
    for (s1, l1), (s2, _) in zip(spans, spans[1:]):
        assert l1 < s2, "allocations overlap"
    names = {n for *_, n in allocs}
    assert any("sentinel" in n for n in names), names


def test_local_rig_allocates_on_comb() -> None:
    _assert_rig_fits_on_comb("rig_https_local")


def test_live_rig_allocates_on_comb() -> None:
    _assert_rig_fits_on_comb("rig_https_live")


def test_bad_finished_rig_allocates_on_comb() -> None:
    _assert_rig_fits_on_comb("rig_https_bad_finished")


def test_the_old_carveout_really_cannot_hold_it() -> None:
    """The fixture reproduces #209: 387 B does not fit the comb tail."""
    with tempfile.TemporaryDirectory() as td:
        labels = Path(td) / "labels.txt"
        labels.write_text(COMB_SEGMENTS)
        _, arb = mp.build_policy_and_arbiter_with_overlay_carveout(
            labels, labels)
        try:
            arb.alloc(256, name="trampoline")
        except Exception as exc:                          # noqa: BLE001
            assert "no free range" in str(exc), exc
        else:
            raise AssertionError("the comb fixture no longer reproduces #209 "
                                 "— the tests above prove nothing on it")


def test_markers_are_one_contiguous_allocation() -> None:
    """The poll reads sentinel+progress as one 2-byte blob; separate allocs
    were only adjacent by first-fit luck. And the clear writes exactly 3."""
    for f in ("rig_https_local.py", "rig_https_live.py",
              "rig_https_bad_finished.py"):
        src = (UCI / f).read_text()
        assert 'arbiter.alloc(3, name="sentinel+progress+carry")' in src, f
        assert "bytes(16)" not in src, (
            f"{f} still clears 16 bytes at the sentinel — 13 past its "
            "3-byte allocation")


def test_unaudited_harness_page3_writer_refuses_the_window() -> None:
    from c64_test_harness.memory_policy import ScratchRegion
    saved = mp.HARNESS_SCRATCH
    mp.HARNESS_SCRATCH = saved + (ScratchRegion(
        0x0350, 0x0360, owner="some.new_helper", purpose="test"),)
    try:
        with tempfile.TemporaryDirectory() as td:
            labels = Path(td) / "labels.txt"
            labels.write_text(COMB_SEGMENTS)
            try:
                mp.build_policy_and_low_ram_arbiter(labels, labels)
            except RuntimeError as exc:
                assert "some.new_helper" in str(exc)
            else:
                raise AssertionError("an unaudited page-3 writer was "
                                     "silently overridden")
    finally:
        mp.HARNESS_SCRATCH = saved


def test_the_window_is_page_three() -> None:
    """$0334 is the first byte above the KERNAL vectors; $0400 is screen
    RAM. Widening either end is a decision, not a tweak."""
    assert mp.LOW_RAM_SCRATCH == (0x0334, 0x03FF), mp.LOW_RAM_SCRATCH


def _fixture_labels() -> dict[str, int]:
    out = {}
    for line in COMB_SEGMENTS.splitlines():
        parts = line.split()
        if len(parts) == 3 and parts[2].startswith("."):
            out[parts[2][1:]] = int(parts[1].split(":")[1], 16)
    return out


def test_each_rig_fits_routine_and_data_in_the_window() -> None:
    """Routine + host + path + the 3 marker bytes, per rig, <= the window.
    Every operand is absolute, so the routine's length is address-free."""
    lo, hi = mp.LOW_RAM_SCRATCH
    window = hi - lo + 1
    labels = _fixture_labels()
    sizes = {}
    for name in ("rig_https_local", "rig_https_bad_finished"):
        mod = importlib.import_module(name)
        code = mod._build_http_routine(labels, 443)[0]
        sizes[name] = (len(code) + mod.HOST_STR_BYTES + mod.PATH_STR_BYTES
                       + 3)
    live = importlib.import_module("rig_https_live")
    code = live.build_live_routine(
        labels, routine_addr=0, host_str_addr=0, path_str_addr=0,
        sentinel_addr=0, progress_addr=1, carry_flag_addr=2, host_len=10,
        port=443)
    sizes["rig_https_live"] = (len(code) + live.HOST_STR_BYTES
                               + live.PATH_STR_BYTES + 3)
    over = {n: v for n, v in sizes.items() if v > window}
    assert not over, f"over the {window} B window: {over}"


def test_no_rig_calls_the_page3_harness_writers() -> None:
    """The audit behind LOW_RAM_HARNESS_WRITERS_UNUSED, kept true."""
    names = {"jsr", "run_subroutine", "play_sid_vice", "liveness_probe",
             "probe_u64", "extract_reu_contents", "extract_snapshot"}
    bad = []
    for p in sorted(UCI.glob("*.py")):
        tree = ast.parse(p.read_text())
        # A script's own helper of the same name (rig_close_retry's
        # opcode-emitting `jsr`) is not the harness routine.
        local = {n.name for n in ast.walk(tree)
                 if isinstance(n, ast.FunctionDef)}
        for n in ast.walk(tree):
            if isinstance(n, ast.Call):
                f = n.func
                fn = f.id if isinstance(f, ast.Name) else getattr(f, "attr", "")
                if fn in names and not (isinstance(f, ast.Name)
                                        and fn in local):
                    bad.append(f"{p.name}:{n.lineno} {fn}()")
    assert not bad, ("a tools/uci script calls a harness routine that writes "
                     f"page 3, the rigs' scratch window: {bad}")


# --------------------------------------------------------------------------
# Every allocating rig, on every UCI profile.

#: The five UCI links a rig can be pointed at. The make lines are the
#: fixture's provenance and what ``--build`` runs.
PROFILES = {
    "uci": "BACKEND=uci",
    "uci-onchip": "BACKEND=uci USE_NISTCURVES_ONCHIP=1",
    "uci-comb": "BACKEND=uci USE_NISTCURVES_ONCHIP_COMB=1",
    "uci-comb-trust": "BACKEND=uci USE_NISTCURVES_ONCHIP_COMB=1 TRUST_STORE=1",
    "uci-comb-demo-trust": (
        "BACKEND=uci USE_NISTCURVES_ONCHIP_COMB=1 TRUST_STORE=1 "
        "HTTPS_HOST=en.wikipedia.org "
        "HTTPS_PATH=/w/index.php?title=Commodore_64&action=raw "
        "HTTPS_BODY_TO_REU=1"),
}
PROFILES_JSON = REPO / "tools" / "rig_scratch_profiles.json"

#: Rigs that run only against a build carrying these labels (a module
#: attribute naming them): elsewhere they refuse before allocating, which
#: is correct, not a scratch failure.
REQUIRES = {
    "rig_trust_store": "NEEDED",           # TRUST_STORE=1
    "rig_https_wiki": "CONTRACT_LABELS",   # HTTPS_BODY_TO_REU=1
}

#: The allocators that hand out a tail of a linked region — what broke
#: here, three times over. No tools/uci script may call them.
TAIL_ALLOCATORS = frozenset({
    "build_arbiter", "build_policy_and_arbiter",
    "build_policy_and_arbiter_with_overlay_carveout",
})

_SEG_LINE = re.compile(r"^al\s+\S+\s+\.__\w+_(START|LAST|SIZE)__\s*$")


def _called_names(path: Path) -> set[str]:
    out = set()
    for n in ast.walk(ast.parse(path.read_text())):
        if isinstance(n, ast.Call):
            f = n.func
            out.add(f.id if isinstance(f, ast.Name) else getattr(f, "attr", ""))
    return out


def allocating_rigs() -> list[str]:
    """Every tools/uci script that builds a scratch policy itself. Wrappers
    that run another rig's main() (print_body, local_p384) inherit it."""
    return sorted(
        p.stem for p in UCI.glob("*.py")
        if not p.name.startswith("_")
        and any(c.startswith("build_policy_and_") for c in _called_names(p)))


def _label_literals() -> set[str]:
    names: set[str] = set()
    for p in UCI.glob("*.py"):
        names |= set(re.findall(r"[\"']([A-Za-z_]\w*)[\"']", p.read_text()))
    return names


def fixture_from_labels(text: str) -> str:
    """Segment markers plus every label a tools/uci script names."""
    want = _label_literals()
    keep = []
    for line in text.splitlines():
        parts = line.split()
        if _SEG_LINE.match(line) or (len(parts) == 3
                                     and parts[2][1:] in want):
            keep.append(line)
    return "\n".join(keep) + "\n"


def _profile_fixtures() -> dict[str, str]:
    data = json.loads(PROFILES_JSON.read_text())
    return {name: data[name]["labels"] for name in PROFILES}


def _windows():
    return (mp.LOW_RAM_SCRATCH_PAGE2, mp.LOW_RAM_SCRATCH)


def check_rig_on_profile(rig: str, labels_text: str) -> str | None:
    """None if `rig` allocates within low RAM on this link, "n/a" if the
    link is not one the rig runs against, else the failure."""
    mod = importlib.import_module(rig)
    present = {ln.split()[2][1:] for ln in labels_text.splitlines()
               if len(ln.split()) == 3}
    req = REQUIRES.get(rig)
    if req and not set(getattr(mod, req)) <= present:
        return "n/a"
    reached, allocs, err, regions = _run_to_lock(rig, labels_text)
    if not reached:
        return f"did not reach the DeviceLock: {err.strip()[-300:]}"
    if not allocs:
        return "reached the DeviceLock without allocating any scratch"
    for start, last, name in allocs:
        if not any(lo <= start <= last <= hi for lo, hi in _windows()):
            return (f"{name} ${start:04X}-${last:04X} is outside the low-RAM "
                    "windows; it moves with the link again")
        for rname, (rs, re_) in regions.items():
            if rname not in mp._SKIP_REGIONS and not (last < rs or start >= re_):
                return f"{name} overlaps declared region {rname}"
    spans = sorted((s, l) for s, l, _ in allocs)
    for (s1, l1), (s2, _) in zip(spans, spans[1:]):
        if l1 >= s2:
            return "allocations overlap"
    return None


def _matrix(fixtures: dict[str, str]) -> list[str]:
    bad, ran = [], {}
    for rig in allocating_rigs():
        for prof, text in fixtures.items():
            why = check_rig_on_profile(rig, text)
            if why == "n/a":
                continue
            ran[rig] = ran.get(rig, 0) + 1
            if why:
                bad.append(f"{rig} on {prof}: {why}")
    for rig in allocating_rigs():
        if not ran.get(rig):
            bad.append(f"{rig} runs on none of {sorted(fixtures)}")
    return bad


def test_every_rig_allocates_on_every_uci_profile() -> None:
    bad = _matrix(_profile_fixtures())
    assert not bad, "\n    " + "\n    ".join(bad)


def test_the_matrix_covers_the_rigs_that_broke() -> None:
    """Discovery must not silently shrink: these six carved a tail and
    failed on comb, and the three #209 rigs and the trust-store rig are
    already low-RAM."""
    rigs = set(allocating_rigs())
    expected = {"phase3_tcp_echo", "bench_ecdsa_u64e", "rig_http_live",
                "rig_http_local", "rig_close_retry", "rig_https_wiki",
                "rig_https_local", "rig_https_live", "rig_https_bad_finished",
                "rig_trust_store"}
    assert expected <= rigs, sorted(expected - rigs)


def test_fixtures_cover_every_profile() -> None:
    data = json.loads(PROFILES_JSON.read_text())
    assert set(data) == set(PROFILES), sorted(set(data) ^ set(PROFILES))
    for name, entry in data.items():
        assert entry["make"] == PROFILES[name], name
        assert "__CRYPTO_OVERLAY_LAST__" in entry["labels"], name


def test_master_comb_tail_cannot_hold_the_old_allocations() -> None:
    """Red half, on the captured master links: the CRYPTO_OVERLAY tail the
    old allocator handed out cannot hold the smallest old request (the
    bench's 320 B stub) on any comb profile."""
    for prof, text in _profile_fixtures().items():
        if "comb" not in prof:
            continue
        with tempfile.TemporaryDirectory() as td:
            labels = Path(td) / "labels.txt"
            labels.write_text(text)
            _, arb = mp.build_policy_and_arbiter(labels, labels)
            try:
                arb.alloc(320, name="ecdsa_stub")
            except Exception as exc:                      # noqa: BLE001
                assert "no free range" in str(exc), exc
            else:
                raise AssertionError(f"{prof}: the old tail fits 320 B — the "
                                     "fixture no longer reproduces the break")


def test_no_rig_carves_a_linked_tail() -> None:
    bad = sorted(f"{p.name}: {sorted(_called_names(p) & TAIL_ALLOCATORS)}"
                 for p in UCI.glob("*.py") if not p.name.startswith("_")
                 and _called_names(p) & TAIL_ALLOCATORS)
    assert not bad, ("a tools/uci script allocates from the tail of a linked "
                     f"region, which moves with every link: {bad}")


def test_page_two_is_outside_every_profile_and_the_harness() -> None:
    """$02A7-$02FF: no captured link declares a region over it, and no
    c64-test-harness writer is declared there."""
    lo, hi = mp.LOW_RAM_SCRATCH_PAGE2
    for prof, text in _profile_fixtures().items():
        with tempfile.TemporaryDirectory() as td:
            labels = Path(td) / "labels.txt"
            labels.write_text(text)
            for name, (rs, re_) in mp._parse_segment_bounds(labels).items():
                if name in mp._SKIP_REGIONS:
                    continue
                assert re_ <= lo or rs > hi, f"{prof}: {name} covers page 2"
    hits = [r for r in mp.HARNESS_SCRATCH if r.start <= hi and r.end > lo]
    assert not hits, hits


def test_page2_window_withholds_the_vectors() -> None:
    with tempfile.TemporaryDirectory() as td:
        labels = Path(td) / "labels.txt"
        labels.write_text(COMB_SEGMENTS)
        policy, arb = mp.build_policy_and_low_ram_arbiter(labels, labels,
                                                          page2=True)
        got = [arb.alloc(1, name=str(i)) for i in range(89 + 204)]
        assert all(not 0x0300 <= a < 0x0334 for a in got)
        assert (min(got), max(got)) == (0x02A7, 0x03FF)
        assert any(r.start == 0x0300 and r.end == 0x0334
                   for r in policy.reserved_regions)


def build_profiles() -> dict[str, dict]:
    """make each profile from clean in this checkout -> fixture entries."""
    out = {}
    for name, line in PROFILES.items():
        subprocess.run(["make", "clean"], cwd=REPO, check=True,
                       capture_output=True)
        r = subprocess.run(["make", *line.split()], cwd=REPO,
                           capture_output=True, text=True)
        if r.returncode:
            raise RuntimeError(f"{name}: make failed\n{r.stdout[-800:]}"
                               f"{r.stderr[-800:]}")
        prg = (REPO / "build" / "c64-https.prg").read_bytes()
        out[name] = {
            "make": line,
            "prg_sha256": hashlib.sha256(prg).hexdigest(),
            "labels": fixture_from_labels(
                (REPO / "build" / "labels.txt").read_text()),
        }
    return out


def main() -> int:
    if "--build" in sys.argv[1:]:
        # Against fresh links of this tree, not the checked-in capture.
        built = build_profiles()
        for name, entry in built.items():
            print(f"  built {name}: {entry['prg_sha256'][:16]}")
        if "--write-fixtures" in sys.argv[1:]:
            PROFILES_JSON.write_text(json.dumps(built, indent=1) + "\n")
            print(f"  wrote {PROFILES_JSON.relative_to(REPO)}")
        bad = _matrix({n: e["labels"] for n, e in built.items()})
        for b in bad:
            print(f"  FAIL  {b}")
        print(f"\nbuilt-profile matrix: {'FAIL' if bad else 'PASS'}")
        if bad:
            return 1
    tests = [(n, f) for n, f in sorted(globals().items())
             if n.startswith("test_") and callable(f)]
    failed = 0
    for name, fn in tests:
        try:
            fn()
            print(f"  PASS  {name}")
        except AssertionError as exc:
            failed += 1
            print(f"  FAIL  {name}: {exc}")
        except Exception as exc:                              # noqa: BLE001
            failed += 1
            print(f"  ERROR {name}: {type(exc).__name__}: {exc}")
    print(f"\n{len(tests) - failed}/{len(tests)} passed")
    from _skip_policy import verdict
    return verdict(len(tests) - failed, failed,
                   certifies="the UCI rigs' low-RAM scratch (#209)")


if __name__ == "__main__":
    sys.exit(main())
