#!/usr/bin/env python3
"""Unit tests for tools/measure_margins.py (#193).

Pure logic: no build, no VICE, no hardware, milliseconds. The fixtures are
verbatim excerpts of a real ip65-onchip link (cfg/c64-https-ip65.cfg's
MEMORY block and that build's map "Segment list"), and the expected
figures were read off that map by hand, so a parser or arithmetic defect
shows up as a wrong number, not as a crash.

The last group parses the real cfgs in cfg/, so a cfg edit that this
tool cannot read (an expression for a bound, say) fails here instead of
at the first person who needs a margin.

Runs under pytest, and standalone::

    python3 tools/test_measure_margins.py
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import measure_margins as mm  # noqa: E402

REPO = Path(__file__).resolve().parent.parent

CFG = """\
# MEMORY { DECOY: start = $1234, size = $10, file = %O; }  <- a comment
MEMORY {
    ZP_CRYPTO:     start = $0022, size = $001E, type = rw, define = yes;
    LOADADDR:      start = $07FF, size = $0002, file = %O;
    LOADER:        start = $0801, size = $17FF, file = %O, define = yes, fill = yes, fillval = $00;
    NET_CODE:      start = $2000, size = $2000, file = %O, define = yes, fill = yes, fillval = $00;
    NET_BSS:        start = $4000, size = $0F8C, file = %O, define = yes, fill = yes, fillval = $00;
    CRYPTO_OVERLAY:     start = $4F8C, size = $1074, file = %O, define = yes, fill = yes, fillval = $00;
    CRYPTO_RESIDENT:    start = $6000, size = $4000, file = %O, define = yes, fill = yes, fillval = $00;
    CRYPTO_COLD_SHADOW: start = $A000, size = $2000, file = %O, define = yes, fill = yes, fillval = $00;
    SCRATCH_UNION:      start = $A000, size = $0600, type = rw, define = yes;
    OVERLAY_BLOB_CURVE_RAM: start = $E000, size = $0000, type = rw, define = yes;
    TCP_BUF:       start = $C000, size = $1000, type = rw, define = yes;
}
SEGMENTS {
    CODE: load = LOADER, type = ro;
}
"""

MAP = """\
Modules list:
-------------
build/boot.o:
    CODE              Offs=000000  Size=000100  Align=00001  Fill=0000

Segment list:
-------------
Name                   Start     End    Size  Align
----------------------------------------------------
LOADADDR              0007FF  000800  000002  00001
EXEHDR                000801  00080C  00000C  00001
CODE                  00080D  001FE5  0017D9  00001
NET_CODE              002000  003B26  001B27  00001
LOADER_OVERFLOW       003B27  003C72  00014C  00001
HTTP_SINK_CODE        003C73  003C74  000002  00001
CRYPTO_AUX_CODE2      003C75  003FB3  00033F  00001
HTTPS_TARGET_RODATA   003FB4  003FC7  000014  00001
TLS_CODE              004F8C  0056FE  000773  00001
CRYPTO_AUX_CODE       0056FF  005D21  000623  00001
HTTP_AUX_CODE         005D22  005EF5  0001D4  00001
HTTP_AUX_CODE2        005EF6  005FB9  0000C4  00001
RODATA                006000  006750  000751  00001
CRYPTO_CODE           006751  007C77  001527  00001
CRYPTO_RODATA         007C78  007DC7  000150  00001
LIB_NISTCURVES_P256_CODE  007DC8  009E71  0020AA  00001
LIB_NISTCURVES_P256_RODATA  009E72  009F31  0000C0  00001
LIB_NISTCURVES_MUL_CODE  009F32  009FD3  0000A2  00001
CERT_BUF_BSS          00A000  00A5FF  000600  00001
LIB_NISTCURVES_P256_BSS  00A000  00A51F  000520  00001
BSS_TAIL              00A600  00A823  000224  00001
LIB_NISTCURVES_BSS    00A824  00A826  000003  00001
BSS                   00A827  00B9C0  00119A  00001
CRYPTO_BSS            00B9C1  00B9D5  000015  00001
TABLES_BSS            00BA00  00BFFF  000600  00100


Exports list by name:
---------------------
"""

STAMP = """\
c64-https build flags. Generated by the Makefile; do not edit.
BACKEND=ip65
CA65FLAGS=-I src -D BACKEND_IP65=1 -D USE_NISTCURVES_ONCHIP=1
LD65FLAGS=-C cfg/c64-https-ip65.cfg -Ln build/labels.txt -m build/c64-https.map
"""


def _raises(fn, *args):
    try:
        fn(*args)
    except mm.ParseError:
        return True
    return False


def _rows():
    return {r["region"]: r for r in mm.measure(mm.parse_cfg_memory(CFG),
                                                mm.parse_map_segments(MAP))}


# --- cfg --------------------------------------------------------------------
def test_cfg_bounds_are_read_not_the_commented_decoy():
    areas = {a["name"]: a for a in mm.parse_cfg_memory(CFG)}
    assert "DECOY" not in areas
    assert (areas["NET_CODE"]["start"], areas["NET_CODE"]["end"]) == (0x2000, 0x3FFF)
    assert (areas["CRYPTO_OVERLAY"]["start"],
            areas["CRYPTO_OVERLAY"]["end"]) == (0x4F8C, 0x5FFF)
    assert areas["CRYPTO_COLD_SHADOW"]["file"] is True
    assert areas["SCRATCH_UNION"]["file"] is False
    assert len(areas) == 11


def test_cfg_expression_bound_is_refused_not_guessed():
    bad = "MEMORY { X: start = $2000, size = $4000 - $2000, file = %O; }"
    assert _raises(mm.parse_cfg_memory, bad)
    assert _raises(mm.parse_cfg_memory, "SEGMENTS { CODE: load = X; }")


def test_cfg_path_comes_from_the_stamp():
    assert mm.cfg_from_stamp(STAMP) == "cfg/c64-https-ip65.cfg"
    mid = STAMP.replace("LD65FLAGS=-C cfg/c64-https-ip65.cfg",
                        "LD65FLAGS=-vm -C cfg/c64-https-uci-onchip.cfg")
    assert mm.cfg_from_stamp(mid) == "cfg/c64-https-uci-onchip.cfg"
    assert _raises(mm.cfg_from_stamp, "LD65FLAGS=-m build/x.map\n")


# --- map --------------------------------------------------------------------
def test_map_segment_list_including_long_names():
    segs = {s["name"]: s for s in mm.parse_map_segments(MAP)}
    assert len(segs) == 25
    assert "Name" not in segs
    lib = segs["LIB_NISTCURVES_P256_RODATA"]
    assert (lib["start"], lib["end"], lib["size"]) == (0x9E72, 0x9F31, 0xC0)


def test_map_inconsistent_or_missing_rows_are_refused():
    assert _raises(mm.parse_map_segments,
                   MAP.replace("003FB4  003FC7  000014", "003FB4  003FC7  000015"))
    assert _raises(mm.parse_map_segments,
                   MAP.replace("TABLES_BSS            00BA00", "TABLES BSS 00BA00"))
    assert _raises(mm.parse_map_segments, "Exports list by name:\n")


# --- measurement ------------------------------------------------------------
def test_tail_is_region_end_minus_last_used():
    rows = _rows()
    assert rows["LOADER"]["tail"] == 0x1FFF - 0x1FE5 == 26
    assert rows["NET_CODE"]["tail"] == 0x3FFF - 0x3FC7 == 56
    assert rows["CRYPTO_OVERLAY"]["tail"] == 0x5FFF - 0x5FB9 == 70
    assert rows["CRYPTO_RESIDENT"]["tail"] == 0x9FFF - 0x9FD3 == 44
    assert rows["CRYPTO_RESIDENT"]["last_used"] == 0x9FD3


def test_interior_hole_is_found_and_union_overlap_is_not_one():
    shadow = _rows()["CRYPTO_COLD_SHADOW"]
    assert shadow["tail"] == 0
    # The alignment gap under page-aligned TABLES_BSS ...
    assert (shadow["hole"], shadow["hole_at"]) == (0xBA00 - 0xB9D6, 0xB9D6) == (42, 0xB9D6)
    # ... and CERT_BUF_BSS / LIB_NISTCURVES_P256_BSS share $A000 without
    # being counted twice.
    assert shadow["used"] == 0x2000 - 42


def test_empty_and_non_file_regions():
    rows = _rows()
    assert rows["NET_BSS"]["empty"] is True and rows["NET_BSS"]["tail"] is None
    for name in ("LOADADDR", "ZP_CRYPTO", "SCRATCH_UNION", "TCP_BUF",
                 "OVERLAY_BLOB_CURVE_RAM"):
        assert name not in rows
    assert list(rows) == ["LOADER", "NET_CODE", "NET_BSS", "CRYPTO_OVERLAY",
                          "CRYPTO_RESIDENT", "CRYPTO_COLD_SHADOW"]


def test_hole_at_region_start():
    areas = mm.parse_cfg_memory(
        "MEMORY { R: start = $1000, size = $0100, file = %O; }")
    segs = [{"name": "A", "start": 0x1010, "end": 0x101F, "size": 0x10},
            {"name": "B", "start": 0x10F0, "end": 0x10FF, "size": 0x10}]
    (row,) = mm.measure(areas, segs)
    assert (row["hole"], row["hole_at"]) == (0xF0 - 0x20, 0x1020)
    assert row["tail"] == 0 and row["overflow"] == 0
    assert row["used"] == 0x10 + 0x10


def test_segment_past_region_end_is_an_overflow_not_a_full_region():
    areas = mm.parse_cfg_memory(
        "MEMORY { R: start = $1000, size = $0100, file = %O;"
        "         S: start = $1100, size = $0100, file = %O; }")
    segs = [{"name": "B", "start": 0x10F0, "end": 0x1120, "size": 0x31},
            {"name": "C", "start": 0x1180, "end": 0x118F, "size": 0x10}]
    rows = {r["region"]: r for r in mm.measure(areas, segs)}
    assert rows["R"]["overflow"] == 0x1120 - 0x10FF == 0x21
    assert rows["S"]["overflow"] == 0
    # B's spill into S is clipped to S's bounds, not counted from B's start.
    assert rows["S"]["used"] == (0x1120 - 0x1100 + 1) + 0x10
    assert rows["R"]["last_used"] == 0x10FF
    assert "OVERFLOWS by 33 B" in mm.format_rows(list(rows.values()))


# ld65 writes the map even when the link fails on an overflow. This is the
# ip65-onchip map with 200 B added to HTTP_AUX_CODE2 (ld65: "overflows
# memory area 'CRYPTO_OVERLAY' by 130 bytes"); the PRG is not written.
FAILED_MAP = MAP.replace("HTTP_AUX_CODE2        005EF6  005FB9  0000C4",
                         "HTTP_AUX_CODE2        005EF6  006081  00018C")


def test_failed_link_map_reports_the_overflow_and_fails():
    rows = mm.measure(mm.parse_cfg_memory(CFG), mm.parse_map_segments(FAILED_MAP))
    byname = {r["region"]: r for r in rows}
    assert byname["CRYPTO_OVERLAY"]["overflow"] == 0x6081 - 0x5FFF == 130
    assert byname["CRYPTO_RESIDENT"]["overflow"] == 0
    bad = mm.failed_links({"x": {"prg_sha256": "ab" * 32, "rows": rows}})
    assert bad and "overflows CRYPTO_OVERLAY by 130 B" in bad[0]


def test_missing_prg_is_a_failed_link_and_a_good_one_is_not():
    rows = list(_rows().values())
    assert mm.failed_links({"x": {"prg_sha256": "ab" * 32, "rows": rows}}) == []
    bad = mm.failed_links({"x": {"prg_sha256": None, "rows": rows}})
    assert len(bad) == 1 and "FAILED link" in bad[0]


def test_missing_build_files_are_a_clean_error():
    import tempfile
    with tempfile.TemporaryDirectory() as d:
        assert _raises(mm.read_build, d)
        rc = mm.main(["--build-dir", d])
    assert rc == 2


def test_format_rows_shows_every_region():
    text = mm.format_rows(list(_rows().values()))
    assert "EMPTY to ld65" in text and "42 B @ $B9D6" in text
    assert "     56 B" in text


# --- the real cfgs ----------------------------------------------------------
def test_every_shipped_cfg_parses_with_the_regions_the_docs_name():
    need = {
        "cfg/c64-https-ip65.cfg": {"LOADER", "NET_CODE", "CRYPTO_OVERLAY",
                                   "CRYPTO_RESIDENT", "CRYPTO_COLD_SHADOW"},
        "cfg/c64-https-uci.cfg": {"LOADER", "NET_CODE", "NET_BSS_TAIL",
                                  "CRYPTO_OVERLAY", "CRYPTO_HOT",
                                  "CRYPTO_COLD_SHADOW"},
        "cfg/c64-https-uci-onchip.cfg": {"LOADER", "NET_CODE", "NET_BSS_TAIL",
                                         "CRYPTO_OVERLAY", "CRYPTO_HOT",
                                         "CRYPTO_COLD_SHADOW"},
    }
    for cfg, regions in need.items():
        areas = {a["name"] for a in mm.parse_cfg_memory((REPO / cfg).read_text())
                 if a["file"]}
        missing = regions - areas
        assert not missing, f"{cfg}: {sorted(missing)} not file-backed MEMORY areas"


def main() -> int:
    tests = [(n, f) for n, f in sorted(globals().items())
             if n.startswith("test_") and callable(f)]
    failed = 0
    for name, fn in tests:
        try:
            fn()
            print(f"  PASS  {name}")
        except AssertionError as exc:
            failed += 1
            print(f"  FAIL  {name}: {exc}")
        except Exception as exc:                              # noqa: BLE001
            failed += 1
            print(f"  ERROR {name}: {type(exc).__name__}: {exc}")
    print(f"\n{len(tests) - failed}/{len(tests)} passed")
    from _skip_policy import verdict
    return verdict(len(tests) - failed, failed,
                   certifies="tools/measure_margins.py's map/cfg parsing")


if __name__ == "__main__":
    sys.exit(main())
