; =============================================================================
; data.asm - Mutable data buffers
; =============================================================================

; =============================================================================
; Zero page save buffer (for ip65 time-sharing)
; =============================================================================
zp_save_buf:    !fill 26, 0     ; saves $02-$1B during ip65 calls

; =============================================================================
; fe25519/x25519 optimization tables — MUST live below $A000 to avoid
; BASIC ROM shadow.  REU DMA and CPU reads need direct RAM access.
; Placed here (early in data section) to guarantee addresses < $A000.
; =============================================================================

; --- REU DMA target buffers (page-aligned for LDA abs,Y without penalty) ---
        !align 255, 0          ; align to next page boundary
mul_dma_lo:
        !fill 256, 0           ; DMA target: lo bytes of a*b for current a
mul_dma_hi:
        !fill 256, 0           ; DMA target: hi bytes of a*b for current a

; --- mult66 second quarter-square table ---
sqtab2_lo:
        !byte 0
        !for i, 1, 255 {
                !byte <(((256-i)*(256-i))/4 - 1)
        }

sqtab2_hi:
        !byte 0
        !for i, 1, 255 {
                !byte >(((256-i)*(256-i))/4 - 1)
        }

; --- mul_by_38 lookup tables ---
mul38_lo_tab:
        !byte 0
        !for i, 1, 255 {
                !byte <(i * 38)
        }

mul38_hi_tab:
        !byte 0
        !for i, 1, 255 {
                !byte >(i * 38)
        }

; --- Quarter-square tables (runtime-generated by sqtab_init in poly1305.asm).
; 512 bytes each (indexed 0..511). Moved from $7800/$7A00 to free up that code region.
        !align 255, 0
sqtab_lo:   !fill 512, 0
sqtab_hi:   !fill 512, 0

; =============================================================================
; Network layer buffers
; =============================================================================
tcp_recv_buf:   !fill 256, 0    ; TCP receive ring buffer (256 bytes, wraps)
tcp_recv_head:  !byte 0         ; read position
tcp_recv_tail:  !byte 0         ; write position (updated by ip65 callback)

; =============================================================================
; TLS state
; =============================================================================
tls_state:              !byte 0         ; current TLS state machine state
tls_last_state:         !byte 0         ; preserves tls_state before error handler overwrites it
tls_recv_progress:      !byte 0         ; granular progress within tls_recv_server_hello
tls_recv_sub_progress:  !byte 0         ; granular progress within tls_record_recv_and_decrypt
tls_recv_poll_count:    !word 0         ; number of sh_wait poll loop iterations (16-bit)
tls_client_random:      !fill 32, 0     ; client random (32 bytes)
tls_server_random:      !fill 32, 0     ; server random (32 bytes)

; ECDHE key exchange
tls_ecdhe_privkey:      !fill 32, 0     ; our ephemeral private key
tls_ecdhe_pubkey:       !fill 32, 0     ; our ephemeral public key (x25519, 32 bytes)
tls_server_pubkey:      !fill 32, 0     ; server's ephemeral public key (x25519, 32 bytes)
tls_shared_secret:      !fill 32, 0     ; ECDHE shared secret (x-coordinate)

; Transcript hash (running SHA-256 state)
tls_transcript:         !fill 32, 0     ; current transcript hash output
tls_transcript_h0:      !fill 4, 0      ; saved SHA-256 state for cloning
tls_transcript_h1:      !fill 4, 0
tls_transcript_h2:      !fill 4, 0
tls_transcript_h3:      !fill 4, 0
tls_transcript_h4:      !fill 4, 0
tls_transcript_h5:      !fill 4, 0
tls_transcript_h6:      !fill 4, 0
tls_transcript_h7:      !fill 4, 0

; Handshake keys (derived from ECDHE via HKDF)
tls_hs_write_key:       !fill 32, 0     ; client handshake write key
tls_hs_write_iv:        !fill 12, 0     ; client handshake write IV
tls_hs_read_key:        !fill 32, 0     ; server handshake read key
tls_hs_read_iv:         !fill 12, 0     ; server handshake read IV

; Application traffic keys (derived after Finished)
tls_app_write_key:      !fill 32, 0     ; client application write key
tls_app_write_iv:       !fill 12, 0     ; client application write IV
tls_app_read_key:       !fill 32, 0     ; server application read key
tls_app_read_iv:        !fill 12, 0     ; server application read IV

; Sequence numbers (64-bit, big-endian)
tls_write_seq:          !fill 8, 0      ; write sequence number
tls_read_seq:           !fill 8, 0      ; read sequence number

; Record layer buffers
tls_rec_header:         !fill 5, 0      ; 5-byte record header
tls_rec_type:           !byte 0         ; content type of current record
tls_rec_len:            !word 0         ; length of current record payload
tls_rec_buf:            !fill 548, 0    ; record payload (512 + 1 inner type + 16 tag + padding)

; AEAD nonce construction
tls_nonce:              !fill 12, 0     ; constructed nonce for AEAD

; Handshake message buffer
tls_hs_buf:             !fill 256, 0    ; handshake message assembly/parsing
tls_hs_len:             !word 0         ; handshake message length

; =============================================================================
; HKDF buffers
; =============================================================================
hkdf_prk:               !fill 32, 0    ; pseudorandom key
hkdf_okm:               !fill 32, 0    ; output keying material
hkdf_info_buf:          !fill 80, 0    ; HkdfLabel construction buffer
hkdf_info_len:          !byte 0
hkdf_salt_ptr:          !word 0
hkdf_salt_len:          !byte 0
hkdf_ikm_ptr:           !word 0
hkdf_ikm_len:           !byte 0
hkdf_label_ptr:         !word 0
hkdf_label_len:         !byte 0
hkdf_context_ptr:       !word 0
hkdf_context_len:       !byte 0
hkdf_out_len:           !byte 0

; TLS key schedule intermediate values
tls_early_secret:       !fill 32, 0    ; HKDF-Extract(0, 0) for PSK=0
tls_handshake_secret:   !fill 32, 0    ; HKDF-Extract(derived, shared_secret)
tls_master_secret:      !fill 32, 0    ; HKDF-Extract(derived, 0)

; =============================================================================
; HTTP buffers
; =============================================================================
http_host_ptr:          !word 0
http_host_len:          !byte 0
http_path_ptr:          !word 0
http_path_len:          !byte 0
http_port:              !word 443       ; default HTTPS port
http_status:            !word 0         ; HTTP status code (e.g., 200)
http_req_buf:           !fill 256, 0    ; HTTP request buffer
http_req_len:           !word 0
http_resp_buf:          !fill 512, 0    ; HTTP response body buffer
http_resp_len:          !word 0

; HTTP parser state
http_parse_state:       !byte 0         ; 0=status line, 1=headers, 2=body
http_hdr_match:         !byte 0         ; consecutive \r\n\r\n match count
http_line_idx:          !byte 0         ; index into status line buffer
http_line_buf:          !fill 32, 0     ; status line accumulator

; =============================================================================
; Application data pointers (for tls_send)
; =============================================================================
tls_app_ptr:            !word 0
tls_app_len:            !word 0

; =============================================================================
; General I/O buffers (used by SHA-256 update)
; =============================================================================
input_buffer:           !fill 256, 0    ; general input buffer
input_length:           !byte 0         ; length of data in input_buffer

; =============================================================================
; SHA-256 working variables (from c64-aes256-ecdsa)
; =============================================================================
sha256_h0:      !fill 4, 0
sha256_h1:      !fill 4, 0
sha256_h2:      !fill 4, 0
sha256_h3:      !fill 4, 0
sha256_h4:      !fill 4, 0
sha256_h5:      !fill 4, 0
sha256_h6:      !fill 4, 0
sha256_h7:      !fill 4, 0

sha_a:          !fill 4, 0
sha_b:          !fill 4, 0
sha_c:          !fill 4, 0
sha_d:          !fill 4, 0
sha_e:          !fill 4, 0
sha_f:          !fill 4, 0
sha_g:          !fill 4, 0
sha_h:          !fill 4, 0

sha_temp3:      !fill 4, 0
sha_t1:         !fill 4, 0
sha_t2:         !fill 4, 0

sha256_block:   !fill 64, 0
sha256_w:       !fill 256, 0    ; message schedule (64 words * 4 bytes)
sha256_hash:    !fill 32, 0     ; final hash output
sha256_len:     !fill 2, 0      ; message length in bits

; =============================================================================
; HMAC-DRBG state (from c64-aes256-ecdsa)
; =============================================================================
hmac_key:       !fill 32, 0     ; HMAC key / DRBG K state
hmac_val:       !fill 32, 0     ; DRBG V state
hmac_opad_block: !fill 64, 0    ; Scratch: K XOR opad
hmac_data_buf:  !fill 97, 0     ; V(32) + 0x00/0x01(1) + seed(64)
hmac_data_len:  !byte 0         ; Length of data in hmac_data_buf
hmac_result:    !fill 32, 0     ; HMAC output
drbg_seed:      !fill 64, 0     ; Seed material (privkey||hash)
drbg_seed_len:  !byte 0         ; Length of seed
drbg_output:    !fill 32, 0     ; Generate output
drbg_buf_idx:   !byte 32        ; Buffer index (32 = empty, forces first generate)

; =============================================================================
; ChaCha20 state (from c64-wireguard)
; =============================================================================
cc20_state:     !fill 64, 0     ; initial state (16 x 32-bit words)
cc20_work:      !fill 64, 0     ; working state during block computation
cc20_keystream: !fill 64, 0     ; generated keystream for XOR
cc20_key:       !fill 32, 0     ; 256-bit key
cc20_nonce:     !fill 12, 0     ; 96-bit nonce
cc20_counter:   !fill 4, 0      ; 32-bit block counter

; =============================================================================
; Poly1305 state (from c64-wireguard)
; =============================================================================
poly_h:         !fill 17, 0     ; 130-bit accumulator
poly_r:         !fill 16, 0     ; clamped key part r
poly_s:         !fill 16, 0     ; key part s (added at end)
poly_product:   !fill 33, 0     ; multiplication scratch (17x16)
poly1305_tag:   !fill 16, 0     ; output tag

; =============================================================================
; AEAD state (from c64-wireguard)
; =============================================================================
aead_key:       !fill 32, 0
aead_nonce:     !fill 12, 0
aead_aad_ptr:   !word 0
aead_aad_len:   !byte 0
aead_data_ptr:  !word 0
aead_data_len:  !byte 0
aead_tag:       !fill 16, 0
aead_scratch:   !fill 16, 0     ; Poly1305 padding/length block

; =============================================================================
; fe25519 field arithmetic (from c64-wireguard)
; =============================================================================
fe_wide:        !fill 64, 0     ; 512-bit product from multiply
fe_tmp1:        !fill 32, 0     ; temporary field element 1
fe_tmp2:        !fill 32, 0     ; temporary field element 2
fe_tmp3:        !fill 32, 0     ; temporary field element 3
fe_tmp4:        !fill 32, 0     ; temporary field element 4

; p = 2^255 - 19 in little-endian
fe_p:
        !byte $ed
        !fill 30, $ff
        !byte $7f

; =============================================================================
; X25519 state (from c64-wireguard)
; =============================================================================
x25_scalar:     !fill 32, 0     ; clamped scalar
x25_u:          !fill 32, 0     ; input u-coordinate
x25_result:     !fill 32, 0     ; output u-coordinate
x25_x2:         !fill 32, 0     ; Montgomery ladder state
x25_z2:         !fill 32, 0
x25_x3:         !fill 32, 0
x25_z3:         !fill 32, 0
x25_a:          !fill 32, 0     ; ladder temporaries
x25_b:          !fill 32, 0
x25_da:         !fill 32, 0
x25_cb:         !fill 32, 0
x25_e:          !fill 32, 0
x25_basepoint:
        !byte 9
        !fill 31, 0

; --- fe_mul optimization buffers (from c64-x25519 optimizations) ---
mul_cached_a:
        !byte 0                ; cached src1[i] for inlined multiply
mul_src2_buf:
        !fill 32, 0           ; absolute copy of src2 for fast indexed access

; =============================================================================
; ECDSA signature verification (moved from ecdsa_verify.asm to avoid
; $7800-$7BFF sqtab memory collision)
; =============================================================================

; --- Verification parameters ---
ecdsa_curve_id:    !byte 0          ; 0=P-256, 1=P-384
ecdsa_hash:        !fill 48, 0      ; message hash (32 for P-256, 48 for P-384)
ecdsa_hash_len:    !byte 32         ; hash length
ecdsa_sig_r:       !fill 48, 0      ; signature r component
ecdsa_sig_s:       !fill 48, 0      ; signature s component
ecdsa_sig_len:     !byte 32         ; component length (32 or 48)
ecdsa_pubkey_x:    !fill 48, 0      ; public key Q.x
ecdsa_pubkey_y:    !fill 48, 0      ; public key Q.y
ecdsa_verify_tmp:  !fill 48, 0      ; temporary for w

; --- P-256 working buffers ---
ev_u1:             !fill 32, 0      ; u1 = z * w mod n
ev_u2:             !fill 32, 0      ; u2 = r * w mod n
ev_point_save:     !fill 96, 0      ; saved Jacobian point (u1*G)

; --- P-384 working buffers ---
ev_u1_384:         !fill 48, 0      ; u1 = z * w mod n (P-384)
ev_u2_384:         !fill 48, 0      ; u2 = r * w mod n (P-384)
ev_point_save_384: !fill 144, 0     ; saved Jacobian point (u1*G, P-384)

; --- DER parsing temporaries ---
ev_der_int_len:    !byte 0          ; current INTEGER length
ev_der_copy_cnt:   !byte 0          ; copy counter
