; data.s — Program-wide BSS and initialized data
; Converted from ACME to ca65 in Phase 3 Batch D.

.include "constants.inc"

.segment "RODATA"

; The X25519 tables (mul38 / sqr / a24) are runtime-generated BSS in
; src/crypto/x25519_tables.s; x25_basepoint and fe_p are the sibling's.

; =============================================================================
; Initialized mutable data (needs DATA segment — small defaults)
; =============================================================================
; Most of these are exported as labels with a nonzero default value.
; ca65's DATA segment isn't declared in the cfg, so we fold them into RODATA
; for now; the code writes to them via absolute stores, which works because
; RODATA resides in RAM ($0801+) on the C64 (the "ro" type in ld65 only
; affects file placement, not runtime writability). If this causes issues
; at Phase 4, move to a proper DATA segment.

.export http_port
http_port:              .word 443       ; default HTTPS port

.export drbg_buf_idx
drbg_buf_idx:           .byte 32        ; Buffer index (32 = empty, forces first generate)

.export ecdsa_hash_len
ecdsa_hash_len:         .byte 32        ; hash length default (P-256)

.export ecdsa_sig_len
ecdsa_sig_len:          .byte 32        ; component length default (32 or 48)

; =============================================================================
; BSS — zero-initialized mutable state
; =============================================================================

.segment "BSS"

; -----------------------------------------------------------------------------
; Zero page save buffer (for ip65 time-sharing)
; -----------------------------------------------------------------------------
.export zp_save_buf
zp_save_buf:    .res 26         ; saves $02-$1B during ip65 calls

; -----------------------------------------------------------------------------
; fe25519/x25519 optimization tables — MUST live below $A000 to avoid
; BASIC ROM shadow. Placed in TABLES_BSS which ld65 maps to the top of the
; CRYPTO region ($6000-$9FFF), keeping them below $A000.
; -----------------------------------------------------------------------------

.segment "TABLES_BSS"

; Multiply-row staging for both libraries: the X25519 sibling's onchip
; fe25519_mul and libs/nistcurves' fp_mul generate (or, REU profile, DMA)
; rows here. Kept first in TABLES_BSS so sqtab_lo lands at $BC00, the
; address both siblings bake in (Makefile post-link check).
.align 256
.export mul_dma_lo
.export mul_dma_hi
mul_dma_lo:     .res 256        ; lo bytes of a*b for current a
mul_dma_hi:     .res 256        ; hi bytes of a*b for current a

; --- Quarter-square tables (runtime-generated by sqtab_init in poly1305.asm) ---
; These remain in-tree under both modes: sqtab_init is still served by
; src/crypto/poly1305.s (the sibling's mul_8x8.s is intentionally
; excluded from build/lib/x25519.a — see tools/integration/build_x25519.sh).
; c64-https OWNS the quarter-square tables in every profile, because it
; owns the §8.0 SQTAB primitive: src/crypto/poly1305.s provides
; `sqtab_init`, and the table a primitive fills belongs to whoever fills it.
;
; This was profile-split before. Under USE_NISTCURVES_ONCHIP the in-tree
; labels yielded to the sibling, which exported sqtab_lo/hi as absolute
; equates baked to LIB_SHARED_SQTAB_BASE, and this file kept a same-size
; `sqtab_reserved` placeholder purely to hold the address still. That
; existed because the sibling's export was unconditional; from the v0.11.2
; pin the wrapper builds it with `-D LIB_NO_BARE_EXPORTS=1` (SPEC §6.5), so
; the bare names are suppressed and the split collapses in the direction
; §8.0 always implied.
;
; THE ADDRESS IS STILL LOAD-BEARING. The sibling reads the table through
; its OWN equates derived from LIB_SHARED_SQTAB_BASE=0xBC00, and derives
; sqtab_hi as base+$0200 (libs/nistcurves/src/mul_8x8.s:47, with its own
; `.assert sqtab_hi = sqtab_lo + $0200`). These labels must therefore land
; at $BC00/$BE00 or every multiply reads the wrong memory — silently, with
; no link error. The Makefile's post-link check asserts sqtab_lo's address.
.align 256
.export sqtab_lo
.export sqtab_hi
sqtab_lo:       .res 512
sqtab_hi:       .res 512

.segment "BSS"

; -----------------------------------------------------------------------------
; Network layer buffers
; -----------------------------------------------------------------------------
; NOTE: tcp_recv_buf itself is an equate in constants.inc pointing at $C000.
.export tcp_recv_head
.export tcp_recv_tail
.export tcp_recv_overflow
tcp_recv_head:      .res 2      ; read position (16-bit, masked with TCP_RECV_MASK)
tcp_recv_tail:      .res 2      ; write position (updated by ip65 callback)
tcp_recv_overflow:  .res 1      ; set to 1 by the backend if the ring
                                ; fills: ACKed bytes lost for good. See
                                ; the set-site comment in
                                ; src/net/ip65/net.s.

; Diagnostic counters — incremented by net_poll at entry and return
.export net_poll_entry_count
.export net_poll_return_count
net_poll_entry_count:   .res 2
net_poll_return_count:  .res 2

; -----------------------------------------------------------------------------
; TLS state
; -----------------------------------------------------------------------------
.export tls_state
.export tls_last_state
.export tls_reached_connected
.export tls_recv_progress
.export tls_recv_sub_progress
.export tls_recv_poll_count
.export tls_client_random
.export tls_server_random
tls_state:              .res 1
tls_last_state:         .res 1
; High-water latch for rigs (#204): TLS_STATE_CONNECTED once the current
; attempt's handshake completes, else 0. Cleared by do_https_get (before
; DNS) and by tls_connect; set only at tls_connect's CONNECTED store.
; tls_close and the error path never touch it, so it outlives the
; CONNECTED window that tls_state holds only until tls_close.
tls_reached_connected:  .res 1
tls_recv_progress:      .res 1
tls_recv_sub_progress:  .res 1
tls_recv_poll_count:    .res 2
tls_client_random:      .res 32
tls_server_random:      .res 32

; ECDHE key exchange
.export tls_ecdhe_privkey
.export tls_ecdhe_pubkey
.export tls_server_pubkey
.export tls_shared_secret
tls_ecdhe_privkey:      .res 32
tls_ecdhe_pubkey:       .res 32
tls_server_pubkey:      .res 32
tls_shared_secret:      .res 32

; Transcript hash (running SHA-256 state)
.export tls_transcript
.export tls_transcript_h0
.export tls_transcript_h1
.export tls_transcript_h2
.export tls_transcript_h3
.export tls_transcript_h4
.export tls_transcript_h5
.export tls_transcript_h6
.export tls_transcript_h7
tls_transcript:         .res 32
tls_transcript_h0:      .res 4
tls_transcript_h1:      .res 4
tls_transcript_h2:      .res 4
tls_transcript_h3:      .res 4
tls_transcript_h4:      .res 4
tls_transcript_h5:      .res 4
tls_transcript_h6:      .res 4
tls_transcript_h7:      .res 4

; Handshake keys (derived from ECDHE via HKDF)
.export tls_hs_write_key
.export tls_hs_write_iv
.export tls_hs_read_key
.export tls_hs_read_iv
tls_hs_write_key:       .res 32
tls_hs_write_iv:        .res 12
tls_hs_read_key:        .res 32
tls_hs_read_iv:         .res 12

; Application traffic keys (derived after Finished)
.export tls_app_write_key
.export tls_app_write_iv
.export tls_app_read_key
.export tls_app_read_iv
tls_app_write_key:      .res 32
tls_app_write_iv:       .res 12
tls_app_read_key:       .res 32
tls_app_read_iv:        .res 12

; Sequence numbers (64-bit, big-endian)
.export tls_write_seq
.export tls_read_seq
tls_write_seq:          .res 8
tls_read_seq:           .res 8

; Record layer buffers
.export tls_rec_header
.export tls_rec_type
.export tls_rec_len
.export tls_rec_buf
tls_rec_header:         .res 5
tls_rec_type:           .res 1
tls_rec_len:            .res 2

; tls_rec_buf (548 B) lives in BSS_TAIL, which every cfg pins in
; CRYPTO_COLD_SHADOW ($A000-$BFFF, RAM under the BASIC ROM): $A000 under
; UCI, $A800 under ip65 (after the cert_buf unions). The X25519 sibling's
; field buffers overlay it (X25519_SCRATCH, issue #245), so it is dead
; across both scalar mults — see the cfgs and tls_recv_server_hello.
; Under ip65 it MUST stay outside the SCRATCH_UNION span: it is live
; during verify.
.segment "BSS_TAIL"
tls_rec_buf:            .res 548
.segment "BSS"

; AEAD nonce construction
.export tls_nonce
tls_nonce:              .res 12

; Handshake messages are parsed and assembled directly in tls_rec_buf /
; tls_rec_len.  The previous tls_hs_buf / tls_hs_len copy staging buffer
; was removed: an 8-bit copy loop truncated records >=256 B (e.g. the
; 352 B Certificate), and tls_hs_buf was too small to hold the
; decrypted plaintext anyway.  tls_rec_buf is 548 B so every fragment
; that fits in our negotiated max_fragment_length of 512 fits there.
; Invariant: handshake handlers (tls_handle_certificate,
; tls_handle_cert_verify, tls_parse_server_hello, ...) must finish
; reading tls_rec_buf before the next record is fetched.  The state
; machine already enforces this (each handler runs synchronously and
; the next-record fetch sits after the handler returns).

; -----------------------------------------------------------------------------
; HKDF buffers
; -----------------------------------------------------------------------------
.export hkdf_prk
.export hkdf_okm
.export hkdf_info_buf
.export hkdf_info_len
.export hkdf_salt_ptr
.export hkdf_salt_len
.export hkdf_ikm_ptr
.export hkdf_ikm_len
.export hkdf_label_ptr
.export hkdf_label_len
.export hkdf_context_ptr
.export hkdf_context_len
.export hkdf_out_len
hkdf_prk:               .res 32
hkdf_okm:               .res 32
hkdf_info_buf:          .res 80
hkdf_info_len:          .res 1
hkdf_salt_ptr:          .res 2
hkdf_salt_len:          .res 1
hkdf_ikm_ptr:           .res 2
hkdf_ikm_len:           .res 1
hkdf_label_ptr:         .res 2
hkdf_label_len:         .res 1
hkdf_context_ptr:       .res 2
hkdf_context_len:       .res 1
hkdf_out_len:           .res 1

; TLS key schedule intermediate values
.export tls_early_secret
.export tls_handshake_secret
.export tls_master_secret
tls_early_secret:       .res 32
tls_handshake_secret:   .res 32
tls_master_secret:      .res 32

; -----------------------------------------------------------------------------
; HTTP buffers
; -----------------------------------------------------------------------------
.export http_host_ptr
.export http_host_len
.export http_path_ptr
.export http_path_len
.export http_status
.export http_req_buf
.export http_req_len
.export http_resp_buf
.export http_resp_len
http_host_ptr:          .res 2
http_host_len:          .res 1
http_path_ptr:          .res 2
http_path_len:          .res 1
http_status:            .res 2
http_req_buf:           .res 256
http_req_len:           .res 2
http_resp_buf:          .res 512
http_resp_len:          .res 2

; HTTP parser state
.export http_parse_state
.export http_hdr_match
.export http_line_idx
.export http_line_buf
.export http_content_length
.export http_cl_valid
.export http_body_total
http_parse_state:       .res 1
http_hdr_match:         .res 1
http_line_idx:          .res 1
http_line_buf:          .res 32
; W4 body-termination fix: Content-Length is 24-bit (real bodies exceed
; 64 KB) and its "absent" state is a separate valid-flag byte instead of
; the historical $FFFF magic (a 24-bit magic could collide with a real
; length).  http_body_total counts body bytes CONSUMED — not stored — so
; the Content-Length termination fires even after the 512 B stored copy
; truncates (the browserleaks.com hang; see src/http.s @state_body).
http_content_length:    .res 3          ; 24-bit LE; meaningful iff http_cl_valid=1
http_cl_valid:          .res 1          ; 1 = Content-Length header seen
http_body_total:        .res 3          ; 24-bit LE count of body bytes consumed

; W4 REU body sink (see src/http.s HTTP_SINK_CODE).  http_body_sink is
; a MODE flag owned by the caller (boot.s under HTTPS_BODY_TO_REU=1, or
; a test/rig via DMA): 0 = classic 512 B buffer capture (default),
; 1 = stream the body to the REU at http_reu_body_base, bouncing
; through http_resp_buf.  It is deliberately NOT reset by the parser.
.export http_body_sink
.export http_reu_cursor
http_body_sink:         .res 1          ; 0 = buffer (default), 1 = REU sink
http_reu_cursor:        .res 3          ; 24-bit LE REU write offset

; -----------------------------------------------------------------------------
; Application data pointers (for tls_send)
; -----------------------------------------------------------------------------
.export tls_app_ptr
.export tls_app_len
tls_app_ptr:            .res 2
tls_app_len:            .res 2

; -----------------------------------------------------------------------------
; General I/O buffers (used by SHA-256 update)
; -----------------------------------------------------------------------------
.export input_buffer
.export input_length
input_buffer:           .res 256
input_length:           .res 1

; -----------------------------------------------------------------------------
; SHA-256 working variables
; -----------------------------------------------------------------------------
.export sha256_h0
.export sha256_h1
.export sha256_h2
.export sha256_h3
.export sha256_h4
.export sha256_h5
.export sha256_h6
.export sha256_h7
sha256_h0:      .res 4
sha256_h1:      .res 4
sha256_h2:      .res 4
sha256_h3:      .res 4
sha256_h4:      .res 4
sha256_h5:      .res 4
sha256_h6:      .res 4
sha256_h7:      .res 4

.export sha_a
.export sha_b
.export sha_c
.export sha_d
.export sha_e
.export sha_f
.export sha_g
.export sha_h
sha_a:          .res 4
sha_b:          .res 4
sha_c:          .res 4
sha_d:          .res 4
sha_e:          .res 4
sha_f:          .res 4
sha_g:          .res 4
sha_h:          .res 4

.export sha_temp3
.export sha_t1
.export sha_t2
sha_temp3:      .res 4
sha_t1:         .res 4
sha_t2:         .res 4

.export sha256_block
.export sha256_w
.export sha256_hash
.export sha256_len
sha256_block:   .res 64
sha256_w:       .res 256        ; message schedule (64 words * 4 bytes)
sha256_hash:    .res 32         ; final hash output
sha256_len:     .res 2          ; message length in bits

; -----------------------------------------------------------------------------
; HMAC-DRBG state
; -----------------------------------------------------------------------------
.export hmac_key
.export hmac_val
.export hmac_opad_block
.export hmac_data_buf
.export hmac_data_len
.export hmac_result
.export drbg_seed
.export drbg_seed_len
.export drbg_output
hmac_key:       .res 32         ; HMAC key / DRBG K state
hmac_val:       .res 32         ; DRBG V state
hmac_opad_block: .res 64        ; Scratch: K XOR opad
hmac_data_buf:  .res 97         ; V(32) + 0x00/0x01(1) + seed(64)
hmac_data_len:  .res 1          ; Length of data in hmac_data_buf
hmac_result:    .res 32         ; HMAC output
drbg_seed:      .res 64         ; Seed material (privkey||hash)
drbg_seed_len:  .res 1          ; Length of seed
drbg_output:    .res 32         ; Generate output

; -----------------------------------------------------------------------------
; ChaCha20 state
; -----------------------------------------------------------------------------
.export cc20_state
.export cc20_work
.export cc20_keystream
.export cc20_key
.export cc20_nonce
.export cc20_counter
cc20_state:     .res 64         ; initial state (16 x 32-bit words)
cc20_work:      .res 64         ; working state during block computation
cc20_keystream: .res 64         ; generated keystream for XOR
cc20_key:       .res 32         ; 256-bit key
cc20_nonce:     .res 12         ; 96-bit nonce
cc20_counter:   .res 4          ; 32-bit block counter

; -----------------------------------------------------------------------------
; Poly1305 state
; -----------------------------------------------------------------------------
.export poly_h
.export poly_r
.export poly_s
.export poly_product
.export poly1305_tag
poly_h:         .res 17         ; 130-bit accumulator
poly_r:         .res 16         ; clamped key part r
poly_s:         .res 16         ; key part s (added at end)
poly_product:   .res 33         ; multiplication scratch (17x16)
poly1305_tag:   .res 16         ; output tag

; -----------------------------------------------------------------------------
; AEAD state
; -----------------------------------------------------------------------------
.export aead_key
.export aead_nonce
.export aead_aad_ptr
.export aead_aad_len
.export aead_data_ptr
.export aead_data_len
.export aead_tag
.export aead_scratch
.export cc20_remain_hi
aead_key:       .res 32
aead_nonce:     .res 12
aead_aad_ptr:   .res 2
aead_aad_len:   .res 1
aead_data_ptr:  .res 2
aead_data_len:  .res 2          ; data length (16-bit; TLS records up to ~4KB)
aead_tag:       .res 16
aead_scratch:   .res 16         ; Poly1305 padding/length block
cc20_remain_hi: .res 1          ; high byte of 16-bit ChaCha20/Poly1305 length counter
                                ; (low byte lives in ZP at cc20_remain = $18)

; -----------------------------------------------------------------------------
; Shared multiply scratch (X25519 sibling + libs/nistcurves fp_mul)
; -----------------------------------------------------------------------------
; The X25519 field/ladder buffers are the sibling's (build_x25519.sh's
; generated module); fe_wide is its ZP_WIDE equate at $40. These two are
; c64-https's because both libraries use them (src/crypto/shared/
; mul_tables.s aliases them to libs/nistcurves' canonical names).
; mul_src2_buf[32] must stay zero: the sibling's fe25519_sqr reads it as a
; phantom slot. fp256's fp_mul re-zeroes bytes 32..34 on every call, and
; BSS starts zeroed.
.export mul_cached_a
.export mul_src2_buf
mul_cached_a:   .res 1          ; cached src1[i] for inlined multiply
mul_src2_buf:   .res 35         ; 32 bytes + 3 zero pad (see above)

; -----------------------------------------------------------------------------
; ECDSA signature verification
; -----------------------------------------------------------------------------

; --- Verification parameters ---
.export ecdsa_curve_id
.export ecdsa_hash
.export ecdsa_sig_r
.export ecdsa_sig_s
.export ecdsa_pubkey_x
.export ecdsa_pubkey_y
.export ecdsa_pubkey_x_384
.export ecdsa_pubkey_y_384
ecdsa_curve_id: .res 1          ; 0=P-256, 1=P-384

; Phase C.4: for P-256, these five 32-byte BE buffers are laid out
; contiguously in memory (r|s|h|Qx|Qy) so the dispatcher can hand
; `ecdsa_sig_r` directly to the sibling's ecdsa_verify_256 as a 160-byte
; packed input struct without an explicit pack step. Reshrunk from 48 B
; to 32 B each; only P-256 is wired right now (P-384 is stubbed — when it
; is re-integrated via a second sibling archive it will own its own
; 240-byte BE input struct, likely reusing this layout scaled to 48 B).
ecdsa_sig_r:    .res 32         ; signature r component (BE, struct +0)
ecdsa_sig_s:    .res 32         ; signature s component (BE, struct +32)
ecdsa_hash:     .res 32         ; message hash            (BE, struct +64)
ecdsa_pubkey_x: .res 32         ; public key Q.x          (BE, struct +96)
ecdsa_pubkey_y: .res 32         ; public key Q.y          (BE, struct +128)

; Phase 5 Fix B: separate 48 B P-384 pubkey slots.  The P-256 packed
; struct above (r|s|h|Qx|Qy contiguous 32 B each) is read verbatim by
; the sibling ecdsa_verify_256, so we can't widen the existing
; ecdsa_pubkey_{x,y} to 48 B without breaking P-256.  The cert handler
; (src/tls_cert.s) targets ecdsa_pubkey_{x,y}_384 when ecdsa_curve_id=1
; and the P-384 dispatcher (src/crypto/ecdsa_verify_384.s) reads from
; the _384 slots.  96 B total in CRYPTO_BSS — well within the slack
; reclaimed by Phase 6's tls_hs_buf removal.
ecdsa_pubkey_x_384: .res 48     ; P-384 public key Q.x  (BE, dispatcher input)
ecdsa_pubkey_y_384: .res 48     ; P-384 public key Q.y  (BE, dispatcher input)

; --- Legacy in-tree ECDSA scratch (ecdsa_verify_tmp, ev_u1, ev_u2,
;     ev_point_save, ev_u1_384, ev_u2_384, ev_point_save_384) was
;     reclaimed in Phase C.4.  The sibling c64-nist-curves
;     `ecdsa_verify_256` now owns its own scratch inside the archive's
;     BSS (ecdsa_w/u1/u2/u1_be/u2_be/u1g_x/u1g_y, fp_rev_buf), so the
;     legacy ev_* labels are unused.  Phase G can reclaim the matching
;     P-384 slots when ecdsa_verify_384 is re-integrated the same way.

; --- DER parsing temporaries ---
.export ev_der_int_len
.export ev_der_copy_cnt
ev_der_int_len: .res 1          ; current INTEGER length
ev_der_copy_cnt: .res 1         ; copy counter
